"use client";
import { useState } from "react";
const CAT_SLUG={"ダンス":"dance","K-POP":"kpop","スイミング":"swimming","プログラミング":"programming","サッカー":"soccer","英語・英会話":"english","ピアノ":"piano","バレエ":"ballet","空手":"karate","リトミック":"rhythmics","幼児教室":"preschool","学習塾":"juku"};
const S = {
  "ダンス": [
    { id:"d0",name:"リディアダンスアカデミー",rating:4.8,rc:45,age:"3歳〜15歳",featured:true,url:"https://re-dia.jp/",desc:"初心者クラスが充実した3歳から学べるキッズダンススクール。現役プロダンサー講師200名以上在籍。全国100校以上展開。千葉市エリアに対応。",tags:["初心者クラス充実","全国100校以上","プロ講師200名以上","初回体験無料","少人数制"],genres:["ヒップホップ","ジャズ","ロック","K-POP","ブレイクダンス","ポップ","ワック"],courses:[{n:"リトルクラス",p:6600,a:"3歳〜6歳"},{n:"キッズクラス",p:7700,a:"小学生"},{n:"月会員プラン",p:7700,a:"全年齢"},{n:"受け放題プラン",p:27000,a:"全年齢"}],locs:[{n:"千葉市校",ad:"千葉県千葉市",st:"最寄駅より徒歩圏内",url:"https://re-dia.jp/"}],revs:[{g:"女の子",a:"5歳〜",l:"千葉市校",t:"先生たちはみんな優しくて毎週楽しみに通っています。"}],color:"#E53935",emoji:"🏆"},
  ],
  "サッカー": [{ id:"s1",name:"リベルタサッカースクール",rating:4.1,rc:12,age:"3歳〜12歳",desc:"「認める・褒める・励ます」の指導で技術とメンタルを育成。",courses:[{n:"通常コース",p:7103,a:"3歳〜12歳"}],locs:[{n:"千葉市校",ad:"千葉県千葉市",st:"最寄駅より徒歩8分"}],revs:[{g:"男の子",a:"5歳〜",l:"千葉市校",t:"上手な子に刺激を受けて頑張るようになりました。"}],color:"#FF9800",emoji:"🏃"}],
  "英語・英会話": [{ id:"e1",name:"ECC KIDS",rating:4.4,rc:180,age:"1歳半〜",desc:"All Englishで自然に英語が身につく。",courses:[{n:"小学生コース",p:11000,a:"6歳〜12歳"}],locs:[{n:"千葉市校",ad:"千葉県千葉市",st:"最寄駅より徒歩3分"}],revs:[{g:"女の子",a:"4歳〜",l:"千葉市校",t:"英語への抵抗がなくなりました。"}],color:"#FF6F00",emoji:"🌍"}],
  "ピアノ": [{ id:"p1",name:"ヤマハ音楽教室",rating:4.5,rc:210,age:"1歳〜",desc:"総合的な音楽力を育てる老舗教室。",courses:[{n:"幼児科",p:7700,a:"4歳〜5歳"}],locs:[{n:"千葉市センター",ad:"千葉県千葉市",st:"最寄駅より徒歩5分"}],revs:[{g:"女の子",a:"4歳〜",l:"千葉市センター",t:"音感がとても良くなりました。"}],color:"#FF5722",emoji:"🎹"}],
  "スイミング": [{ id:"sw1",name:"コナミスポーツクラブ",rating:4.3,rc:95,age:"6ヶ月〜",desc:"段階的な進級制度でステップアップ。",courses:[{n:"キッズ",p:8250,a:"3歳〜"}],locs:[{n:"千葉市店",ad:"千葉県千葉市",st:"最寄駅より徒歩5分"}],revs:[{g:"男の子",a:"4歳〜",l:"千葉市店",t:"クロール25m泳げるようになりました。"}],color:"#03A9F4",emoji:"🏊"}],
  "バレエ": [{ id:"b1",name:"千葉市バレエスタジオ",rating:4.4,rc:30,age:"3歳〜",desc:"アットホームな雰囲気で初心者でも安心。",courses:[{n:"ジュニア",p:7700,a:"小学生"}],locs:[{n:"千葉市スタジオ",ad:"千葉県千葉市",st:"最寄駅より徒歩5分"}],revs:[{g:"女の子",a:"5歳〜",l:"千葉市スタジオ",t:"姿勢が良くなりました。"}],color:"#9C27B0",emoji:"🩰"}],
  "空手": [{ id:"k1",name:"千葉市空手道場",rating:4.5,rc:35,age:"4歳〜",desc:"礼儀作法と強い心を育てる。",courses:[{n:"少年部",p:7700,a:"4歳〜12歳"}],locs:[{n:"千葉市道場",ad:"千葉県千葉市",st:"最寄駅より徒歩5分"}],revs:[{g:"男の子",a:"5歳〜",l:"千葉市道場",t:"粘り強さが身につきました。"}],color:"#F44336",emoji:"🥋"}],
  "K-POP": [{ id:"kp0",name:"リディアダンスアカデミー",rating:4.8,rc:45,age:"3歳〜15歳",featured:true,url:"https://re-dia.jp/",desc:"K-POPダンスクラスも充実！プロ講師200名以上在籍、全国100校以上。",tags:["K-POPクラス充実","全国100校以上","プロ講師200名以上","初回体験無料"],genres:["K-POP","ヒップホップ","ジャズ"],courses:[{n:"月会員プラン",p:7700,a:"全年齢"}],locs:[{n:"千葉市校",ad:"千葉県千葉市",st:"最寄駅より徒歩圏内",url:"https://re-dia.jp/"}],revs:[{g:"女の子",a:"8歳〜",l:"千葉市校",t:"K-POPの曲で踊れるのがとても楽しい！"}],color:"#E53935",emoji:"🏆"}],
  "リトミック": [{ id:"rt1",name:"カワイ リトミック教室",rating:4.4,rc:88,age:"1歳〜",desc:"音楽で感性と表現力を育みます。",courses:[{n:"1歳クラス",p:5500,a:"1歳"}],locs:[{n:"千葉市教室",ad:"千葉県千葉市",st:"最寄駅より徒歩5分"}],revs:[{g:"女の子",a:"1歳〜",l:"千葉市教室",t:"リズム感がついてきました。"}],color:"#FF7043",emoji:"🎵"}],
  "幼児教室": [{ id:"yj1",name:"ベビーパーク",rating:4.4,rc:95,age:"0歳〜3歳",desc:"知育プログラムで考える力を伸ばします。",courses:[{n:"Aクラス",p:15400,a:"0歳〜"}],locs:[{n:"千葉市教室",ad:"千葉県千葉市",st:"最寄駅より徒歩3分"}],revs:[{g:"男の子",a:"0歳〜",l:"千葉市教室",t:"言葉の発達がとても早くなりました。"}],color:"#FF8A65",emoji:"🧒"}],
  "学習塾": [{ id:"gk1",name:"公文式教室",rating:4.3,rc:250,age:"3歳〜",desc:"自学自習で基礎学力を鍛えます。",courses:[{n:"算数・数学",p:7700,a:"3歳〜"}],locs:[{n:"千葉市駅前教室",ad:"千葉県千葉市",st:"最寄駅より徒歩2分"}],revs:[{g:"男の子",a:"5歳〜",l:"千葉市駅前教室",t:"無理なく学力がつきました。"}],color:"#1E88E5",emoji:"📝"}],
};
const CATS=[{name:"ダンス",count:30,icon:"💃"},{name:"サッカー",count:22,icon:"⚽"},{name:"英語・英会話",count:35,icon:"🌍"},{name:"ピアノ",count:38,icon:"🎹"},{name:"スイミング",count:14,icon:"🏊"},{name:"バレエ",count:15,icon:"🩰"},{name:"空手",count:10,icon:"🥋"},{name:"K-POP",count:8,icon:"💜"},{name:"リトミック",count:12,icon:"🎵"},{name:"幼児教室",count:14,icon:"🧒"},{name:"学習塾",count:48,icon:"📝"}];
const INFO={"ダンス":{fee:"5,000〜10,000円",age:"3歳〜",skills:"リズム感・柔軟性・集中力・協調性",desc:"千葉市では大手チェーンから地域密着型まで多彩なダンス教室が展開しています。"},"サッカー":{fee:"3,000〜8,000円",age:"3歳〜",skills:"体力・瞬発力・協調性",desc:"チームプレーで協調性が身につく人気スポーツ。"},"英語・英会話":{fee:"8,000〜15,000円",age:"1歳半〜",skills:"リスニング・発音・異文化理解",desc:"幼少期からの英語教育で発音とリスニング力を高めます。"},"ピアノ":{fee:"6,000〜10,000円",age:"3歳〜",skills:"音感・集中力・忍耐力",desc:"脳の発達に効果的なピアノ。"},"スイミング":{fee:"6,000〜9,000円",age:"6ヶ月〜",skills:"体力・持久力・心肺機能",desc:"全身運動で体力向上。"},"バレエ":{fee:"6,000〜12,000円",age:"3歳〜",skills:"柔軟性・姿勢・表現力",desc:"美しい姿勢と柔軟性が身につきます。"},"空手":{fee:"5,000〜8,000円",age:"3歳〜",skills:"礼儀・集中力・忍耐力",desc:"礼儀作法を重視する心身の鍛錬。"},"K-POP":{fee:"7,000〜16,000円",age:"4歳〜",skills:"リズム感・表現力・協調性",desc:"大人気のK-POPダンスで楽しく学べます。"},"リトミック":{fee:"4,000〜6,000円",age:"0歳〜",skills:"リズム感・表現力・感性",desc:"0歳から始められる音楽教育。"},"幼児教室":{fee:"10,000〜16,000円",age:"0歳〜",skills:"記憶力・思考力・集中力",desc:"知育プログラムで考える力を伸ばします。"},"学習塾":{fee:"7,000〜33,000円",age:"3歳〜",skills:"基礎学力・思考力・受験対策",desc:"基礎学力から受験対策まで。"}};
function Stars({r,c}){if(!r)return <span style={{color:"#999",fontSize:13}}>口コミはありません</span>;return(<span style={{display:"inline-flex",alignItems:"center",gap:3}}>{[...Array(5)].map((_,i)=>(<span key={i} style={{color:i<Math.round(r)?"#FFB300":"#ddd",fontSize:15}}>{i<Math.round(r)?"★":"☆"}</span>))}<b style={{color:"#333",fontSize:14,marginLeft:3}}>{r}</b><span style={{color:"#888",fontSize:12}}>({c}件)</span></span>);}
function Acc({title,color,open,toggle,children}){return(<div style={{padding:"10px 22px 0"}}><button onClick={toggle} style={{background:"none",border:`1px solid ${color||"#e0e0e0"}33`,borderRadius:10,padding:"9px 14px",width:"100%",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"space-between",fontSize:13,fontWeight:700,color:color||"#444"}}><span>{title}</span><span style={{transform:open?"rotate(180deg)":"",transition:".2s"}}>▼</span></button>{open&&<div style={{marginTop:10}}>{children}</div>}</div>);}
function CRow({c,color,i}){return(<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"9px 12px",background:i%2===0?"#fafbfc":"#fff",borderRadius:8,marginBottom:3}}><div><div style={{fontSize:13,fontWeight:600,color:"#333"}}>{c.n}</div><div style={{fontSize:11,color:"#999"}}>{c.a}</div></div><div style={{fontSize:15,fontWeight:800,color:color}}>{c.p?`¥${c.p.toLocaleString()}`:"要問合せ"}{c.p&&<span style={{fontSize:10,fontWeight:400,color:"#999"}}>/月</span>}</div></div>);}
function LocRow({l,color,last}){return(<div style={{padding:"8px 0",borderBottom:last?"none":"1px solid #f0f0f0"}}>{l.url?<a href={l.url} target="_blank" rel="noopener noreferrer" style={{fontSize:13,fontWeight:700,color:"#1565C0",textDecoration:"none"}}>📍 {l.n}</a>:<div style={{fontSize:13,fontWeight:700,color:"#333"}}>📍 {l.n}</div>}<div style={{fontSize:11,color:"#888",marginTop:2}}>{l.ad}</div><div style={{fontSize:11,color:color,marginTop:2}}>🚃 {l.st}</div></div>);}
function Card({s,idx,catName}){const[exp,setExp]=useState(false);const[loc,setLoc]=useState(false);
return(<article style={{background:s.featured?"linear-gradient(135deg,#fff,#FFF8F7)":"#fff",borderRadius:16,boxShadow:s.featured?`0 8px 40px ${s.color}18`:"0 2px 14px rgba(0,0,0,.06)",overflow:"hidden",border:s.featured?`2px solid ${s.color}22`:"1px solid #f0f0f0",position:"relative"}}>{s.featured&&<div style={{position:"absolute",top:0,left:22,background:"linear-gradient(135deg,#FFD700,#FFA000)",color:"#fff",fontWeight:900,fontSize:12,padding:"5px 12px 8px",borderRadius:"0 0 10px 10px",zIndex:2}}>👑 おすすめNo.1</div>}<header style={{display:"flex",alignItems:"center",padding:s.featured?"38px 22px 0":"16px 20px 0",gap:12}}><div style={{width:s.featured?68:52,height:s.featured?68:52,borderRadius:16,background:`linear-gradient(135deg,${s.color}22,${s.color}44)`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:s.featured?34:26,flexShrink:0}}>{s.emoji}</div><div style={{flex:1}}><h2 style={{margin:0,fontSize:s.featured?19:16,fontWeight:900,color:"#1a1a2e"}}>{s.name}</h2><div style={{display:"flex",alignItems:"center",gap:6,marginTop:6,flexWrap:"wrap"}}><span style={{background:`${s.color}18`,color:s.color,padding:"3px 9px",borderRadius:20,fontSize:11,fontWeight:700}}>{catName}</span><span style={{color:"#666",fontSize:12}}>{s.age}</span></div></div></header><div style={{padding:"10px 22px 0"}}><Stars r={s.rating} c={s.rc}/></div><p style={{padding:"10px 22px 0",margin:0,fontSize:14,color:"#444",lineHeight:1.8}}>{s.desc}</p>{s.revs?.[0]&&<div style={{margin:"12px 22px 0",background:"#f8f9fb",borderRadius:10,padding:12,borderLeft:`3px solid ${s.color}`}}><p style={{margin:0,fontSize:13,color:"#555",lineHeight:1.6}}>「{s.revs[0].t}」</p></div>}<Acc title={`📋 コース（${s.courses.length}件）`} color={s.color} open={exp} toggle={()=>setExp(!exp)}>{s.courses.map((c,i)=><CRow key={i} c={c} color={s.color} i={i}/>)}</Acc><Acc title={`📍 教室（${s.locs.length}件）`} color={s.color} open={loc} toggle={()=>setLoc(!loc)}>{s.locs.map((l,i)=><LocRow key={i} l={l} color={s.color} last={i===s.locs.length-1}/>)}</Acc><div style={{padding:"18px 22px"}}>{s.url?<a href={s.url} target="_blank" rel="noopener noreferrer" style={{display:"flex",alignItems:"center",justifyContent:"center",gap:8,padding:"14px",borderRadius:14,background:`linear-gradient(135deg,${s.color},${s.color}cc)`,color:"#fff",fontWeight:800,fontSize:14,textDecoration:"none"}}>📝 無料体験レッスンに申し込む</a>:<button style={{width:"100%",padding:"13px",borderRadius:12,border:"none",background:`linear-gradient(135deg,${s.color},${s.color}cc)`,color:"#fff",fontWeight:700,fontSize:14,cursor:"pointer"}}>📝 無料体験レッスンに申し込む</button>}</div></article>);}
export default function App(){
  const[cat,setCat]=useState("ダンス");const[search,setSearch]=useState("");
  const schools=S[cat]||[];const filtered=schools.filter(s=>!search||s.name.includes(search)||s.desc.includes(search));const info=INFO[cat]||{};const catData=CATS.find(c=>c.name===cat);
  return(<div style={{fontFamily:"'Noto Sans JP','Hiragino Sans',sans-serif",background:"#f5f6fa",minHeight:"100vh"}}><style>{`*{box-sizing:border-box;margin:0;padding:0}`}</style>
    <header style={{background:"linear-gradient(135deg,#C62828,#B71C1C)",color:"#fff",position:"sticky",top:0,zIndex:100,boxShadow:"0 4px 20px rgba(0,0,0,.15)"}}><div style={{maxWidth:1100,margin:"0 auto",padding:"12px 20px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><a href="/" style={{display:"flex",alignItems:"center",gap:10,textDecoration:"none",color:"inherit"}}><span style={{fontSize:26}}>🧒</span><div><div style={{fontSize:18,fontWeight:900}}>コドモならいごと</div><div style={{fontSize:10,opacity:.8}}>子供の習い事を口コミで比較</div></div></a><span style={{fontSize:12,opacity:.9}}>📍 千葉市</span></div></header>
    <div style={{maxWidth:1100,margin:"0 auto",padding:"20px 20px 0"}}><div style={{background:"linear-gradient(135deg,#FFEBEE,#FFCDD2,#FCE4EC)",borderRadius:20,padding:"28px 24px"}}><h1 style={{fontSize:22,fontWeight:900,color:"#1a1a2e",margin:0}}>千葉市の<span style={{color:"#C62828"}}>{cat}スクール</span>おすすめ一覧<span style={{fontSize:13,fontWeight:400,color:"#888"}}>【2026年最新】</span></h1><div style={{marginTop:16}}><input type="text" placeholder="🔍 スクール名で検索..." value={search} onChange={e=>setSearch(e.target.value)} style={{width:"100%",padding:"11px 16px",borderRadius:12,border:"2px solid #e0e0e0",fontSize:14,outline:"none",background:"#fff"}}/></div></div></div>
    <nav style={{maxWidth:1100,margin:"0 auto",padding:"18px 20px 0"}}><div style={{display:"flex",gap:7,overflowX:"auto",paddingBottom:8}}>{CATS.map(c=><button key={c.name} onClick={()=>{setCat(c.name);setSearch("");}} style={{display:"inline-flex",alignItems:"center",gap:5,padding:"7px 14px",borderRadius:24,whiteSpace:"nowrap",cursor:"pointer",border:cat===c.name?"2px solid #C62828":"2px solid #e8e8e8",background:cat===c.name?"linear-gradient(135deg,#C62828,#B71C1C)":"#fff",color:cat===c.name?"#fff":"#555",fontWeight:cat===c.name?700:500,fontSize:13}}><span>{c.icon}</span><span>{c.name}</span></button>)}</div></nav>
    <main style={{maxWidth:1100,margin:"0 auto",padding:"14px 20px 40px",display:"flex",flexDirection:"column",gap:18}}>{filtered.map((s,i)=><Card key={s.id} s={s} idx={i} catName={cat}/>)}</main>
    <footer style={{background:"linear-gradient(135deg,#1a1a2e,#16213e)",color:"#aab",padding:"28px 20px"}}><div style={{maxWidth:1100,margin:"0 auto"}}><div style={{display:"flex",flexWrap:"wrap",gap:14,marginBottom:14}}><a href="/" style={{color:"#ccc",fontSize:13,textDecoration:"none"}}>🏠 トップ</a><a href="/chiba" style={{color:"#ccc",fontSize:13,textDecoration:"none"}}>千葉県の習い事</a><a href="/about" style={{color:"#aab",fontSize:12,textDecoration:"none"}}>会社概要</a><a href="/privacy" style={{color:"#aab",fontSize:12,textDecoration:"none"}}>プライバシー</a></div><div style={{fontSize:11,color:"#667"}}>© 2026 コドモならいごと</div></div></footer>
  </div>);
}
