// /app/basketball/basketballData.js

const SPORTS_DEPOT = { name: "スポーツデポ バスケット教室", rating: 4.2, fee: 5500, age: "3歳〜", desc: "全国展開のスポーツショップが運営。基礎から楽しくバスケットを学べる。", color: "#E65100", emoji: "🏀" };
const MINI_BASKET = { name: "ミニバスケットボールクラブ", rating: 4.3, fee: 3300, age: "小学生〜", desc: "地域密着型のミニバスケットクラブ。チームワークと基礎技術を習得。", color: "#BF360C", emoji: "🏀" };
const DREAM_COURT = { name: "バスケットボールスクール ドリームコート", rating: 4.4, fee: 6600, age: "4歳〜", desc: "専門コーチによる技術指導。ドリブル・シュート・パスの基礎を楽しく学ぶ。", color: "#E65100", emoji: "⭐" };

function localSchool(name, area, desc, fee = 5500, rating = 4.2) {
  return { name, rating, fee, age: "3歳〜", desc: desc || `${area}に根ざしたバスケットボールスクール。少人数制で丁寧な指導を行い、専門コーチが在籍。`, color: "#E65100", emoji: "🏀" };
}

const STD_FAQS = (prefName) => [
  { q: `${prefName}で何歳からバスケを習えますか？`, a: "3〜4歳から通えるキッズクラスがあります。ミニバスケットボール対応の幼児コースを設けているスクールも多くあります。" },
  { q: `${prefName}のバスケットボールスクールの月謝相場は？`, a: "週1回で3,000〜7,000円が一般的です。Bリーグクラブ運営のスクールは5,000〜8,000円程度が多いです。" },
  { q: "女の子でもバスケを習えますか？", a: "もちろんです。女子バスケも人気が高まっており、多くのスクールで男女問わず受け入れています。" },
  { q: "バスケを習う効果は？", a: "瞬発力・判断力・チームワーク・背が伸びやすくなる効果も期待できます。運動能力全般が向上します。" },
];

const STD_BLOGS = [
  { href: "/blog/kids-soccer-benefits-guide", text: "体を動かす習い事のメリット" },
  { href: "/blog/kids-activity-ranking-all", text: "子供の習い事人気ランキング" },
  { href: "/blog/kids-sports-dance-comparison", text: "スポーツ系習い事比較" },
];

export const BASKETBALL_PREFS = {
  osaka: {
    name: "大阪府",
    heroText: "関西最大都市・大阪のバスケットボールスクール・教室",
    areas: [
      { slug: "osaka-city", name: "大阪市" },
      { slug: "minoh", name: "箕面市" },
      { slug: "moriguchi", name: "守口市" },
      { slug: "sakai", name: "堺市" },
      { slug: "suita", name: "吹田市" },
      { slug: "takatsuki", name: "高槻市" },
      { slug: "toyonaka", name: "豊中市" },
      { slug: "ibaraki", name: "茨木市" },
    ],
    schools: [
      localSchool("大阪エヴェッサ バスケットボールスクール", "大阪", "Bリーグ・大阪エヴェッサが運営。プロの環境で基礎から本格的に学べる。", 6600, 4.5),
      DREAM_COURT,
      SPORTS_DEPOT,
      MINI_BASKET,
      localSchool("大阪バスケットボールアカデミー", "大阪", "専門指導者によるキッズ〜ジュニア対象のバスケ教室。個人技術とチームプレーを習得。"),
    ],
    faqs: STD_FAQS("大阪府"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "kanagawa", name: "神奈川県" },
      { slug: "aichi", name: "愛知県" }, { slug: "kyoto", name: "京都府" },
      { slug: "hyogo", name: "兵庫県" },
    ],
  },
  tokyo: {
    name: "東京都",
    heroText: "首都・東京の子ども向けバスケットボールスクール・教室",
    areas: [
      { slug: "chofu", name: "調布市" }, { slug: "edogawa", name: "江戸川区" },
      { slug: "kita", name: "北区" }, { slug: "machida", name: "町田市" },
      { slug: "meguro", name: "目黒区" }, { slug: "minato", name: "港区" },
      { slug: "nerima", name: "練馬区" }, { slug: "setagaya", name: "世田谷区" },
      { slug: "shibuya", name: "渋谷区" }, { slug: "shinagawa", name: "品川区" },
      { slug: "shinjuku", name: "新宿区" }, { slug: "suginami", name: "杉並区" },
    ],
    schools: [
      localSchool("東京バスケットボールアカデミー", "東京", "元プロ選手コーチによる本格指導。ドリブル・シュート・パス技術を段階的に習得。", 7700, 4.6),
      DREAM_COURT,
      SPORTS_DEPOT,
      MINI_BASKET,
      localSchool("キッズバスケット東京", "東京", "幼児〜小学生対象の楽しいバスケットボール教室。基礎体力と協調性を育む。"),
    ],
    faqs: STD_FAQS("東京都"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "kanagawa", name: "神奈川県" }, { slug: "saitama", name: "埼玉県" },
      { slug: "chiba", name: "千葉県" }, { slug: "osaka", name: "大阪府" },
    ],
  },
  kanagawa: {
    name: "神奈川県",
    heroText: "横浜・川崎を擁する神奈川県のバスケットボールスクール・教室",
    areas: [
      { slug: "aoba", name: "青葉区" }, { slug: "atsugi", name: "厚木市" },
      { slug: "ebina", name: "海老名市" }, { slug: "fujisawa", name: "藤沢市" },
      { slug: "kohoku", name: "港北区" }, { slug: "midori", name: "緑区" },
      { slug: "nakahara", name: "中原区" }, { slug: "nakahara-shinjou", name: "中原区（新城）" },
      { slug: "sagamihara", name: "相模原市" }, { slug: "takatsu", name: "高津区" },
      { slug: "tsuzuki", name: "都筑区" }, { slug: "yamato", name: "大和市" },
      { slug: "yokosuka", name: "横須賀市" }, { slug: "zushi", name: "逗子市" },
    ],
    schools: [
      localSchool("川崎ブレイブサンダース バスケットボールスクール", "神奈川", "Bリーグ・川崎ブレイブサンダースが運営。プロクラブの本格指導が受けられる。", 7150, 4.6),
      DREAM_COURT,
      SPORTS_DEPOT,
      MINI_BASKET,
      localSchool("神奈川バスケットボールアカデミー", "神奈川", "幼児〜ジュニア向けのバスケ教室。個人技術からチームプレーまで段階的に指導。"),
    ],
    faqs: STD_FAQS("神奈川県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "chiba", name: "千葉県" }, { slug: "shizuoka", name: "静岡県" },
    ],
  },
  aichi: {
    name: "愛知県",
    heroText: "名古屋を中心とした愛知県のバスケットボールスクール・教室",
    areas: [
      { slug: "anjo", name: "安城市" }, { slug: "chikusa", name: "千種区" },
      { slug: "meito", name: "名東区" }, { slug: "midori", name: "緑区" },
      { slug: "moriyama", name: "守山区" }, { slug: "nisshin", name: "日進市" },
      { slug: "owariasahi", name: "尾張旭市" }, { slug: "tenpaku", name: "天白区" },
      { slug: "toyota", name: "豊田市" },
    ],
    schools: [
      localSchool("名古屋ダイヤモンドドルフィンズ バスケットボールスクール", "愛知", "Bリーグ・名古屋ダイヤモンドドルフィンズ関連スクール。専門コーチによる本格指導。", 6600, 4.5),
      DREAM_COURT,
      SPORTS_DEPOT,
      MINI_BASKET,
      localSchool("愛知バスケットボールアカデミー", "愛知", "名古屋エリアの本格バスケット教室。ドリブル・シュート・パスを楽しく習得。"),
    ],
    faqs: STD_FAQS("愛知県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "gifu", name: "岐阜県" },
      { slug: "shizuoka", name: "静岡県" }, { slug: "mie", name: "三重県" },
    ],
  },
  gifu: {
    name: "岐阜県",
    heroText: "岐阜県の子ども向けバスケットボールスクール・教室",
    areas: [
      { slug: "gifu-city", name: "岐阜市" }, { slug: "kani", name: "可児市" },
      { slug: "minokamo", name: "美濃加茂市" }, { slug: "tajimi", name: "多治見市" },
    ],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("ぎふバスケットボールスクール", "岐阜"),
      localSchool("岐阜キッズバスケットクラブ", "岐阜", "岐阜県内の子ども向けバスケット教室。楽しみながら基礎技術を身につける。"),
    ],
    faqs: STD_FAQS("岐阜県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "aichi", name: "愛知県" }, { slug: "shizuoka", name: "静岡県" },
      { slug: "nagano", name: "長野県" }, { slug: "mie", name: "三重県" },
    ],
  },
  hyogo: {
    name: "兵庫県",
    heroText: "神戸・西宮を擁する兵庫県のバスケットボールスクール・教室",
    areas: [
      { slug: "nishinomiya", name: "西宮市" },
    ],
    schools: [
      localSchool("神戸ストークス バスケットボールスクール", "兵庫", "神戸を拠点とするバスケットボールクラブ系列のスクール。専門コーチが丁寧に指導。", 6050, 4.4),
      DREAM_COURT,
      SPORTS_DEPOT,
      MINI_BASKET,
      localSchool("兵庫バスケットボールアカデミー", "兵庫"),
    ],
    faqs: STD_FAQS("兵庫県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "kyoto", name: "京都府" },
      { slug: "nara", name: "奈良県" }, { slug: "wakayama", name: "和歌山県" },
    ],
  },
  ibaraki: {
    name: "茨城県",
    heroText: "茨城県の子ども向けバスケットボールスクール・教室",
    areas: [
      { slug: "hitachi", name: "日立市" }, { slug: "hitachinaka", name: "ひたちなか市" },
      { slug: "mito", name: "水戸市" }, { slug: "tsuchiura", name: "土浦市" },
      { slug: "tsukuba", name: "つくば市" },
    ],
    schools: [
      localSchool("茨城ロボッツ バスケットボールスクール", "茨城", "Bリーグ・茨城ロボッツ関連スクール。プロチームと連携した専門指導。", 5500, 4.4),
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("茨城バスケットボールアカデミー", "茨城"),
    ],
    faqs: STD_FAQS("茨城県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "chiba", name: "千葉県" }, { slug: "tochigi", name: "栃木県" },
    ],
  },
  ishikawa: {
    name: "石川県",
    heroText: "金沢を中心とした石川県のバスケットボールスクール・教室",
    areas: [
      { slug: "kanazawa", name: "金沢市" }, { slug: "nonoichi", name: "野々市市" },
      { slug: "uchinada", name: "内灘町" },
    ],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("金沢バスケットボールスクール", "石川"),
      localSchool("石川キッズバスケットクラブ", "石川", "石川県内の幼児〜小学生対象のバスケット教室。少人数制で丁寧な指導。"),
    ],
    faqs: STD_FAQS("石川県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "toyama", name: "富山県" }, { slug: "fukui", name: "福井県" },
      { slug: "niigata", name: "新潟県" }, { slug: "nagano", name: "長野県" },
    ],
  },
  kyoto: {
    name: "京都府",
    heroText: "古都・京都の子ども向けバスケットボールスクール・教室",
    areas: [
      { slug: "kyoto-city", name: "京都市" },
    ],
    schools: [
      localSchool("京都ハンナリーズ バスケットボールスクール", "京都", "Bリーグ・京都ハンナリーズ関連スクール。プロの指導メソッドで基礎から本格指導。", 6600, 4.5),
      DREAM_COURT,
      SPORTS_DEPOT,
      MINI_BASKET,
      localSchool("京都バスケットボールアカデミー", "京都"),
    ],
    faqs: STD_FAQS("京都府"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "hyogo", name: "兵庫県" },
      { slug: "shiga", name: "滋賀県" }, { slug: "nara", name: "奈良県" },
    ],
  },
  nagano: {
    name: "長野県",
    heroText: "長野県の子ども向けバスケットボールスクール・教室",
    areas: [
      { slug: "nagano-city", name: "長野市" },
    ],
    schools: [
      localSchool("信州ブレイブウォリアーズ バスケットボールスクール", "長野", "Bリーグ・信州ブレイブウォリアーズ関連スクール。地域密着型の本格指導。", 5500, 4.4),
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("長野バスケットボールアカデミー", "長野"),
    ],
    faqs: STD_FAQS("長野県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "aichi", name: "愛知県" },
      { slug: "gifu", name: "岐阜県" }, { slug: "niigata", name: "新潟県" },
    ],
  },
  shiga: {
    name: "滋賀県",
    heroText: "琵琶湖を擁する滋賀県のバスケットボールスクール・教室",
    areas: [
      { slug: "kusatsu", name: "草津市" }, { slug: "otsu", name: "大津市" },
    ],
    schools: [
      localSchool("滋賀レイクス バスケットボールスクール", "滋賀", "Bリーグ・滋賀レイクス関連スクール。プロチームの指導ノウハウを活かした教室。", 5500, 4.4),
      DREAM_COURT,
      SPORTS_DEPOT,
      MINI_BASKET,
      localSchool("しがバスケットボールアカデミー", "滋賀"),
    ],
    faqs: STD_FAQS("滋賀県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "kyoto", name: "京都府" },
      { slug: "hyogo", name: "兵庫県" }, { slug: "mie", name: "三重県" },
    ],
  },
  wakayama: {
    name: "和歌山県",
    heroText: "和歌山県の子ども向けバスケットボールスクール・教室",
    areas: [
      { slug: "wakayama-city", name: "和歌山市" },
    ],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("わかやまバスケットボールスクール", "和歌山"),
      localSchool("和歌山キッズバスケットクラブ", "和歌山", "和歌山県内の子ども向けバスケット教室。楽しく基礎技術を習得。"),
    ],
    faqs: STD_FAQS("和歌山県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "hyogo", name: "兵庫県" },
      { slug: "nara", name: "奈良県" }, { slug: "mie", name: "三重県" },
    ],
  },
  saitama: {
    name: "埼玉県",
    heroText: "埼玉県の子ども向けバスケットボールスクール・教室",
    areas: [
      { slug: "kawaguchi", name: "川口市" }, { slug: "koshigaya", name: "越谷市" },
      { slug: "minami", name: "南区" }, { slug: "urawa", name: "浦和区" },
    ],
    schools: [
      localSchool("埼玉ブロンコスOB バスケットボールスクール", "埼玉", "埼玉を拠点とするバスケットボールクラブ系列スクール。専門コーチによる丁寧な指導。", 5500, 4.3),
      DREAM_COURT,
      SPORTS_DEPOT,
      MINI_BASKET,
      localSchool("さいたまバスケットボールアカデミー", "埼玉"),
    ],
    faqs: STD_FAQS("埼玉県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "kanagawa", name: "神奈川県" },
      { slug: "chiba", name: "千葉県" }, { slug: "gunma", name: "群馬県" },
    ],
  },
  chiba: {
    name: "千葉県",
    heroText: "千葉県の子ども向けバスケットボールスクール・教室",
    areas: [
      { slug: "chiba-city", name: "千葉市" }, { slug: "kashiwa", name: "柏市" },
      { slug: "matsudo", name: "松戸市" },
    ],
    schools: [
      localSchool("千葉ジェッツ バスケットボールスクール", "千葉", "Bリーグ・千葉ジェッツが運営する公式スクール。プロの指導メソッドで基礎から本格的に学べる。", 7700, 4.7),
      DREAM_COURT,
      SPORTS_DEPOT,
      MINI_BASKET,
      localSchool("千葉バスケットボールアカデミー", "千葉", "千葉エリアの子ども向けバスケ教室。元プロ選手コーチによる熱心な指導。"),
    ],
    faqs: STD_FAQS("千葉県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "kanagawa", name: "神奈川県" }, { slug: "ibaraki", name: "茨城県" },
    ],
  },
  fukuoka: {
    name: "福岡県",
    heroText: "九州最大の都市・福岡のバスケットボールスクール・教室",
    areas: [],
    schools: [
      localSchool("福岡レッドファルコンズ バスケットボールスクール", "福岡", "九州を代表するバスケットボールクラブ系列スクール。専門コーチによる本格指導。", 5500, 4.3),
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("福岡バスケットボールアカデミー", "福岡"),
    ],
    faqs: STD_FAQS("福岡県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "saga", name: "佐賀県" }, { slug: "nagasaki", name: "長崎県" },
      { slug: "kumamoto", name: "熊本県" }, { slug: "oita", name: "大分県" },
    ],
  },
  hokkaido: {
    name: "北海道",
    heroText: "北海道の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      localSchool("レバンガ北海道 バスケットボールスクール", "北海道", "Bリーグ・レバンガ北海道関連スクール。北海道の子どもたちにバスケットを広める。", 5500, 4.4),
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("北海道バスケットボールアカデミー", "北海道"),
    ],
    faqs: STD_FAQS("北海道"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "aomori", name: "青森県" }, { slug: "iwate", name: "岩手県" },
      { slug: "miyagi", name: "宮城県" }, { slug: "akita", name: "秋田県" },
    ],
  },
  miyagi: {
    name: "宮城県",
    heroText: "仙台を擁する宮城県のバスケットボールスクール・教室",
    areas: [],
    schools: [
      localSchool("仙台89ERS バスケットボールスクール", "宮城", "Bリーグ・仙台89ERS関連スクール。仙台エリアの子どもたちに本格的なバスケ指導。", 5500, 4.4),
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("宮城バスケットボールアカデミー", "宮城"),
    ],
    faqs: STD_FAQS("宮城県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "fukushima", name: "福島県" }, { slug: "yamagata", name: "山形県" },
      { slug: "iwate", name: "岩手県" }, { slug: "akita", name: "秋田県" },
    ],
  },
  hiroshima: {
    name: "広島県",
    heroText: "広島県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      localSchool("広島ドラゴンフライズ バスケットボールスクール", "広島", "Bリーグ・広島ドラゴンフライズ関連スクール。専門コーチによる本格指導。", 5500, 4.4),
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("広島バスケットボールアカデミー", "広島"),
    ],
    faqs: STD_FAQS("広島県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "okayama", name: "岡山県" }, { slug: "yamaguchi", name: "山口県" },
      { slug: "shimane", name: "島根県" }, { slug: "tottori", name: "鳥取県" },
    ],
  },
  shizuoka: {
    name: "静岡県",
    heroText: "静岡県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("静岡バスケットボールスクール", "静岡"),
      localSchool("静岡キッズバスケットクラブ", "静岡", "静岡県内の幼児〜小学生対象のバスケット教室。楽しく基礎を習得。"),
    ],
    faqs: STD_FAQS("静岡県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "aichi", name: "愛知県" }, { slug: "kanagawa", name: "神奈川県" },
      { slug: "nagano", name: "長野県" }, { slug: "yamanashi", name: "山梨県" },
    ],
  },
  okayama: {
    name: "岡山県",
    heroText: "岡山県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("岡山バスケットボールスクール", "岡山"),
      localSchool("岡山キッズバスケットクラブ", "岡山", "岡山県内の子ども向けバスケット教室。専門コーチが基礎から丁寧に指導。"),
    ],
    faqs: STD_FAQS("岡山県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "hiroshima", name: "広島県" }, { slug: "tottori", name: "鳥取県" },
      { slug: "hyogo", name: "兵庫県" }, { slug: "kagawa", name: "香川県" },
    ],
  },
  niigata: {
    name: "新潟県",
    heroText: "新潟県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      localSchool("新潟アルビレックスBB バスケットボールスクール", "新潟", "Bリーグ・新潟アルビレックスBB関連スクール。地域密着型の本格指導。", 5500, 4.4),
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("新潟バスケットボールアカデミー", "新潟"),
    ],
    faqs: STD_FAQS("新潟県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "nagano", name: "長野県" }, { slug: "fukushima", name: "福島県" },
      { slug: "yamagata", name: "山形県" }, { slug: "toyama", name: "富山県" },
    ],
  },
  tochigi: {
    name: "栃木県",
    heroText: "栃木県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      localSchool("宇都宮ブレックス バスケットボールスクール", "栃木", "Bリーグ屈指の強豪・宇都宮ブレックス関連スクール。高水準の指導環境。", 6600, 4.6),
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("栃木バスケットボールアカデミー", "栃木"),
    ],
    faqs: STD_FAQS("栃木県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "gunma", name: "群馬県" }, { slug: "ibaraki", name: "茨城県" },
    ],
  },
  gunma: {
    name: "群馬県",
    heroText: "群馬県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("群馬バスケットボールスクール", "群馬"),
      localSchool("群馬キッズバスケットクラブ", "群馬", "群馬県内の子ども向けバスケット教室。楽しく基礎を習得。"),
    ],
    faqs: STD_FAQS("群馬県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "tochigi", name: "栃木県" }, { slug: "nagano", name: "長野県" },
    ],
  },
  mie: {
    name: "三重県",
    heroText: "三重県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("三重バスケットボールスクール", "三重"),
      localSchool("三重キッズバスケットクラブ", "三重", "三重県内の幼児〜小学生対象のバスケット教室。"),
    ],
    faqs: STD_FAQS("三重県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "aichi", name: "愛知県" }, { slug: "osaka", name: "大阪府" },
      { slug: "kyoto", name: "京都府" }, { slug: "nara", name: "奈良県" },
    ],
  },
  nara: {
    name: "奈良県",
    heroText: "奈良県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("奈良バスケットボールスクール", "奈良"),
      localSchool("奈良キッズバスケットクラブ", "奈良", "奈良県内の子ども向けバスケット教室。専門コーチが指導。"),
    ],
    faqs: STD_FAQS("奈良県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "kyoto", name: "京都府" },
      { slug: "hyogo", name: "兵庫県" }, { slug: "wakayama", name: "和歌山県" },
    ],
  },
  fukui: {
    name: "福井県",
    heroText: "福井県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("福井バスケットボールスクール", "福井"),
      localSchool("福井キッズバスケットクラブ", "福井", "福井県内の幼児〜小学生対象のバスケット教室。"),
    ],
    faqs: STD_FAQS("福井県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "ishikawa", name: "石川県" }, { slug: "toyama", name: "富山県" },
      { slug: "gifu", name: "岐阜県" }, { slug: "kyoto", name: "京都府" },
    ],
  },
  toyama: {
    name: "富山県",
    heroText: "富山県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("富山バスケットボールスクール", "富山"),
      localSchool("富山キッズバスケットクラブ", "富山", "富山県内の子ども向けバスケット教室。楽しく基礎技術を習得。"),
    ],
    faqs: STD_FAQS("富山県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "ishikawa", name: "石川県" }, { slug: "fukui", name: "福井県" },
      { slug: "niigata", name: "新潟県" }, { slug: "nagano", name: "長野県" },
    ],
  },
  yamanashi: {
    name: "山梨県",
    heroText: "山梨県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("山梨バスケットボールスクール", "山梨"),
      localSchool("山梨キッズバスケットクラブ", "山梨", "山梨県内の幼児〜小学生対象のバスケット教室。"),
    ],
    faqs: STD_FAQS("山梨県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "kanagawa", name: "神奈川県" },
      { slug: "shizuoka", name: "静岡県" }, { slug: "nagano", name: "長野県" },
    ],
  },
  tottori: {
    name: "鳥取県",
    heroText: "鳥取県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("鳥取バスケットボールスクール", "鳥取"),
      localSchool("鳥取キッズバスケットクラブ", "鳥取", "鳥取県内の子ども向けバスケット教室。専門コーチが指導。"),
    ],
    faqs: STD_FAQS("鳥取県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "shimane", name: "島根県" }, { slug: "okayama", name: "岡山県" },
      { slug: "hiroshima", name: "広島県" }, { slug: "hyogo", name: "兵庫県" },
    ],
  },
  shimane: {
    name: "島根県",
    heroText: "島根県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("島根バスケットボールスクール", "島根"),
      localSchool("島根キッズバスケットクラブ", "島根", "島根県内の幼児〜小学生対象のバスケット教室。楽しく基礎を習得。"),
    ],
    faqs: STD_FAQS("島根県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tottori", name: "鳥取県" }, { slug: "hiroshima", name: "広島県" },
      { slug: "yamaguchi", name: "山口県" }, { slug: "okayama", name: "岡山県" },
    ],
  },
  kochi: {
    name: "高知県",
    heroText: "高知県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("高知バスケットボールスクール", "高知"),
      localSchool("高知キッズバスケットクラブ", "高知", "高知県内の子ども向けバスケット教室。"),
    ],
    faqs: STD_FAQS("高知県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokushima", name: "徳島県" }, { slug: "ehime", name: "愛媛県" },
      { slug: "kagawa", name: "香川県" }, { slug: "hiroshima", name: "広島県" },
    ],
  },
  tokushima: {
    name: "徳島県",
    heroText: "徳島県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("徳島バスケットボールスクール", "徳島"),
      localSchool("徳島キッズバスケットクラブ", "徳島", "徳島県内の幼児〜小学生対象のバスケット教室。"),
    ],
    faqs: STD_FAQS("徳島県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "kagawa", name: "香川県" }, { slug: "ehime", name: "愛媛県" },
      { slug: "kochi", name: "高知県" }, { slug: "hyogo", name: "兵庫県" },
    ],
  },
  kagawa: {
    name: "香川県",
    heroText: "香川県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("高松バスケットボールスクール", "香川"),
      localSchool("香川キッズバスケットクラブ", "香川", "香川県内の子ども向けバスケット教室。楽しく技術を習得。"),
    ],
    faqs: STD_FAQS("香川県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "tokushima", name: "徳島県" }, { slug: "ehime", name: "愛媛県" },
      { slug: "kochi", name: "高知県" }, { slug: "okayama", name: "岡山県" },
    ],
  },
  saga: {
    name: "佐賀県",
    heroText: "佐賀県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("佐賀バスケットボールスクール", "佐賀"),
      localSchool("佐賀キッズバスケットクラブ", "佐賀", "佐賀県内の幼児〜小学生対象のバスケット教室。"),
    ],
    faqs: STD_FAQS("佐賀県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "nagasaki", name: "長崎県" },
      { slug: "kumamoto", name: "熊本県" }, { slug: "oita", name: "大分県" },
    ],
  },
  oita: {
    name: "大分県",
    heroText: "大分県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("大分バスケットボールスクール", "大分"),
      localSchool("大分キッズバスケットクラブ", "大分", "大分県内の子ども向けバスケット教室。専門コーチが基礎から丁寧に指導。"),
    ],
    faqs: STD_FAQS("大分県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "kumamoto", name: "熊本県" },
      { slug: "miyazaki", name: "宮崎県" }, { slug: "ehime", name: "愛媛県" },
    ],
  },
  miyazaki: {
    name: "宮崎県",
    heroText: "宮崎県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("宮崎バスケットボールスクール", "宮崎"),
      localSchool("宮崎キッズバスケットクラブ", "宮崎", "宮崎県内の幼児〜小学生対象のバスケット教室。"),
    ],
    faqs: STD_FAQS("宮崎県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "oita", name: "大分県" },
      { slug: "kumamoto", name: "熊本県" }, { slug: "kagoshima", name: "鹿児島県" },
    ],
  },
  okinawa: {
    name: "沖縄県",
    heroText: "沖縄県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      localSchool("琉球ゴールデンキングス バスケットボールスクール", "沖縄", "Bリーグ・琉球ゴールデンキングス関連スクール。沖縄の子どもたちに本格的なバスケを。", 5500, 4.5),
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("沖縄バスケットボールアカデミー", "沖縄"),
    ],
    faqs: STD_FAQS("沖縄県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "kagoshima", name: "鹿児島県" }, { slug: "fukuoka", name: "福岡県" },
      { slug: "miyazaki", name: "宮崎県" }, { slug: "kumamoto", name: "熊本県" },
    ],
  },
  kumamoto: {
    name: "熊本県",
    heroText: "熊本県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("熊本バスケットボールスクール", "熊本"),
      localSchool("熊本キッズバスケットクラブ", "熊本", "熊本県内の幼児〜小学生対象のバスケット教室。楽しく基礎を習得。"),
    ],
    faqs: STD_FAQS("熊本県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "saga", name: "佐賀県" },
      { slug: "nagasaki", name: "長崎県" }, { slug: "oita", name: "大分県" },
    ],
  },
  kagoshima: {
    name: "鹿児島県",
    heroText: "鹿児島県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("鹿児島バスケットボールスクール", "鹿児島"),
      localSchool("鹿児島キッズバスケットクラブ", "鹿児島", "鹿児島県内の子ども向けバスケット教室。専門コーチが指導。"),
    ],
    faqs: STD_FAQS("鹿児島県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "kumamoto", name: "熊本県" },
      { slug: "miyazaki", name: "宮崎県" }, { slug: "okinawa", name: "沖縄県" },
    ],
  },
  nagasaki: {
    name: "長崎県",
    heroText: "長崎県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("長崎バスケットボールスクール", "長崎"),
      localSchool("長崎キッズバスケットクラブ", "長崎", "長崎県内の幼児〜小学生対象のバスケット教室。楽しく技術を習得。"),
    ],
    faqs: STD_FAQS("長崎県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "saga", name: "佐賀県" },
      { slug: "kumamoto", name: "熊本県" }, { slug: "oita", name: "大分県" },
    ],
  },
  ehime: {
    name: "愛媛県",
    heroText: "愛媛県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("愛媛バスケットボールスクール", "愛媛"),
      localSchool("愛媛キッズバスケットクラブ", "愛媛", "愛媛県内の子ども向けバスケット教室。専門コーチが基礎から丁寧に指導。"),
    ],
    faqs: STD_FAQS("愛媛県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "kagawa", name: "香川県" }, { slug: "tokushima", name: "徳島県" },
      { slug: "kochi", name: "高知県" }, { slug: "hiroshima", name: "広島県" },
    ],
  },
  yamaguchi: {
    name: "山口県",
    heroText: "山口県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("山口バスケットボールスクール", "山口"),
      localSchool("山口キッズバスケットクラブ", "山口", "山口県内の幼児〜小学生対象のバスケット教室。"),
    ],
    faqs: STD_FAQS("山口県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "hiroshima", name: "広島県" }, { slug: "shimane", name: "島根県" },
      { slug: "fukuoka", name: "福岡県" }, { slug: "tottori", name: "鳥取県" },
    ],
  },
  fukushima: {
    name: "福島県",
    heroText: "福島県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("福島バスケットボールスクール", "福島"),
      localSchool("福島キッズバスケットクラブ", "福島", "福島県内の子ども向けバスケット教室。楽しく基礎技術を習得。"),
    ],
    faqs: STD_FAQS("福島県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "miyagi", name: "宮城県" }, { slug: "yamagata", name: "山形県" },
      { slug: "ibaraki", name: "茨城県" }, { slug: "niigata", name: "新潟県" },
    ],
  },
  akita: {
    name: "秋田県",
    heroText: "秋田県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("秋田バスケットボールスクール", "秋田"),
      localSchool("秋田キッズバスケットクラブ", "秋田", "秋田県内の幼児〜小学生対象のバスケット教室。専門コーチが指導。"),
    ],
    faqs: STD_FAQS("秋田県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "miyagi", name: "宮城県" }, { slug: "iwate", name: "岩手県" },
      { slug: "yamagata", name: "山形県" }, { slug: "aomori", name: "青森県" },
    ],
  },
  yamagata: {
    name: "山形県",
    heroText: "山形県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("山形バスケットボールスクール", "山形"),
      localSchool("山形キッズバスケットクラブ", "山形", "山形県内の子ども向けバスケット教室。楽しく技術を習得。"),
    ],
    faqs: STD_FAQS("山形県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "miyagi", name: "宮城県" }, { slug: "akita", name: "秋田県" },
      { slug: "fukushima", name: "福島県" }, { slug: "niigata", name: "新潟県" },
    ],
  },
  iwate: {
    name: "岩手県",
    heroText: "岩手県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("岩手バスケットボールスクール", "岩手"),
      localSchool("岩手キッズバスケットクラブ", "岩手", "岩手県内の幼児〜小学生対象のバスケット教室。"),
    ],
    faqs: STD_FAQS("岩手県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "miyagi", name: "宮城県" }, { slug: "akita", name: "秋田県" },
      { slug: "aomori", name: "青森県" }, { slug: "fukushima", name: "福島県" },
    ],
  },
  aomori: {
    name: "青森県",
    heroText: "青森県の子ども向けバスケットボールスクール・教室",
    areas: [],
    schools: [
      SPORTS_DEPOT,
      MINI_BASKET,
      DREAM_COURT,
      localSchool("青森バスケットボールスクール", "青森"),
      localSchool("青森キッズバスケットクラブ", "青森", "青森県内の子ども向けバスケット教室。楽しく基礎技術を習得。"),
    ],
    faqs: STD_FAQS("青森県"),
    blogs: STD_BLOGS,
    otherPrefs: [
      { slug: "iwate", name: "岩手県" }, { slug: "akita", name: "秋田県" },
      { slug: "miyagi", name: "宮城県" }, { slug: "hokkaido", name: "北海道" },
    ],
  },
};

// ────────────────────────────────────────────
// BASKETBALL_AREAS: エリア別データ
// ────────────────────────────────────────────

function areaSchools(areaName, prefName, chain1, chain2, chain3, chain4) {
  return [
    { ...chain1, desc: chain1.desc },
    { ...chain2, desc: chain2.desc },
    { ...chain3, desc: chain3.desc },
    { ...(chain4 || SPORTS_DEPOT), desc: (chain4 || SPORTS_DEPOT).desc },
    localSchool(`${areaName}バスケットボールスクール`, areaName),
  ];
}

export const BASKETBALL_AREAS = {
  // ── 大阪府 ──
  "osaka/osaka-city": { name: "大阪市", prefName: "大阪府", prefSlug: "osaka", schools: areaSchools("大阪市", "大阪府", localSchool("大阪エヴェッサ バスケットボールスクール", "大阪市", "Bリーグ・大阪エヴェッサが運営。プロの環境で基礎から本格的に学べる。", 6600, 4.5), DREAM_COURT, SPORTS_DEPOT, MINI_BASKET) },
  "osaka/minoh": { name: "箕面市", prefName: "大阪府", prefSlug: "osaka", schools: areaSchools("箕面市", "大阪府", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("箕面バスケットボールスクール", "箕面")) },
  "osaka/moriguchi": { name: "守口市", prefName: "大阪府", prefSlug: "osaka", schools: areaSchools("守口市", "大阪府", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("守口バスケットボールスクール", "守口")) },
  "osaka/sakai": { name: "堺市", prefName: "大阪府", prefSlug: "osaka", schools: areaSchools("堺市", "大阪府", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("堺バスケットボールスクール", "堺")) },
  "osaka/suita": { name: "吹田市", prefName: "大阪府", prefSlug: "osaka", schools: areaSchools("吹田市", "大阪府", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("吹田バスケットボールスクール", "吹田")) },
  "osaka/takatsuki": { name: "高槻市", prefName: "大阪府", prefSlug: "osaka", schools: areaSchools("高槻市", "大阪府", SPORTS_DEPOT, DREAM_COURT, MINI_BASKET, localSchool("高槻バスケットボールスクール", "高槻")) },
  "osaka/toyonaka": { name: "豊中市", prefName: "大阪府", prefSlug: "osaka", schools: areaSchools("豊中市", "大阪府", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("豊中バスケットボールスクール", "豊中")) },
  "osaka/ibaraki": { name: "茨木市", prefName: "大阪府", prefSlug: "osaka", schools: areaSchools("茨木市", "大阪府", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("茨木バスケットボールスクール", "茨木")) },
  // ── 愛知県 ──
  "aichi/anjo": { name: "安城市", prefName: "愛知県", prefSlug: "aichi", schools: areaSchools("安城市", "愛知県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("安城バスケットボールスクール", "安城")) },
  "aichi/chikusa": { name: "千種区", prefName: "愛知県", prefSlug: "aichi", schools: areaSchools("千種区", "愛知県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("千種バスケットボールスクール", "千種")) },
  "aichi/meito": { name: "名東区", prefName: "愛知県", prefSlug: "aichi", schools: areaSchools("名東区", "愛知県", DREAM_COURT, MINI_BASKET, SPORTS_DEPOT, localSchool("名東バスケットボールスクール", "名東")) },
  "aichi/midori": { name: "緑区", prefName: "愛知県", prefSlug: "aichi", schools: areaSchools("緑区", "愛知県", SPORTS_DEPOT, DREAM_COURT, MINI_BASKET, localSchool("緑区バスケットボールスクール", "緑区")) },
  "aichi/moriyama": { name: "守山区", prefName: "愛知県", prefSlug: "aichi", schools: areaSchools("守山区", "愛知県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("守山バスケットボールスクール", "守山")) },
  "aichi/nisshin": { name: "日進市", prefName: "愛知県", prefSlug: "aichi", schools: areaSchools("日進市", "愛知県", SPORTS_DEPOT, DREAM_COURT, MINI_BASKET, localSchool("日進バスケットボールスクール", "日進")) },
  "aichi/owariasahi": { name: "尾張旭市", prefName: "愛知県", prefSlug: "aichi", schools: areaSchools("尾張旭市", "愛知県", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("尾張旭バスケットボールスクール", "尾張旭")) },
  "aichi/tenpaku": { name: "天白区", prefName: "愛知県", prefSlug: "aichi", schools: areaSchools("天白区", "愛知県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("天白バスケットボールスクール", "天白")) },
  "aichi/toyota": { name: "豊田市", prefName: "愛知県", prefSlug: "aichi", schools: areaSchools("豊田市", "愛知県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("豊田バスケットボールスクール", "豊田")) },
  // ── 千葉県 ──
  "chiba/chiba-city": { name: "千葉市", prefName: "千葉県", prefSlug: "chiba", schools: areaSchools("千葉市", "千葉県", localSchool("千葉ジェッツ バスケットボールスクール", "千葉市", "Bリーグ・千葉ジェッツが運営する公式スクール。プロの指導メソッドで基礎から本格的に学べる。", 7700, 4.7), DREAM_COURT, SPORTS_DEPOT, MINI_BASKET) },
  "chiba/kashiwa": { name: "柏市", prefName: "千葉県", prefSlug: "chiba", schools: areaSchools("柏市", "千葉県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("柏バスケットボールスクール", "柏")) },
  "chiba/matsudo": { name: "松戸市", prefName: "千葉県", prefSlug: "chiba", schools: areaSchools("松戸市", "千葉県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("松戸バスケットボールスクール", "松戸")) },
  // ── 岐阜県 ──
  "gifu/gifu-city": { name: "岐阜市", prefName: "岐阜県", prefSlug: "gifu", schools: areaSchools("岐阜市", "岐阜県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("岐阜バスケットボールスクール", "岐阜")) },
  "gifu/kani": { name: "可児市", prefName: "岐阜県", prefSlug: "gifu", schools: areaSchools("可児市", "岐阜県", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("可児バスケットボールスクール", "可児")) },
  "gifu/minokamo": { name: "美濃加茂市", prefName: "岐阜県", prefSlug: "gifu", schools: areaSchools("美濃加茂市", "岐阜県", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("美濃加茂バスケットボールスクール", "美濃加茂")) },
  "gifu/tajimi": { name: "多治見市", prefName: "岐阜県", prefSlug: "gifu", schools: areaSchools("多治見市", "岐阜県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("多治見バスケットボールスクール", "多治見")) },
  // ── 兵庫県 ──
  "hyogo/nishinomiya": { name: "西宮市", prefName: "兵庫県", prefSlug: "hyogo", schools: areaSchools("西宮市", "兵庫県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("西宮バスケットボールスクール", "西宮")) },
  // ── 茨城県 ──
  "ibaraki/hitachi": { name: "日立市", prefName: "茨城県", prefSlug: "ibaraki", schools: areaSchools("日立市", "茨城県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("日立バスケットボールスクール", "日立")) },
  "ibaraki/hitachinaka": { name: "ひたちなか市", prefName: "茨城県", prefSlug: "ibaraki", schools: areaSchools("ひたちなか市", "茨城県", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("ひたちなかバスケットボールスクール", "ひたちなか")) },
  "ibaraki/mito": { name: "水戸市", prefName: "茨城県", prefSlug: "ibaraki", schools: areaSchools("水戸市", "茨城県", localSchool("茨城ロボッツ バスケットボールスクール 水戸", "水戸", "Bリーグ・茨城ロボッツ関連スクール。水戸エリアでプロ連携の本格指導。", 5500, 4.4), SPORTS_DEPOT, MINI_BASKET, DREAM_COURT) },
  "ibaraki/tsuchiura": { name: "土浦市", prefName: "茨城県", prefSlug: "ibaraki", schools: areaSchools("土浦市", "茨城県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("土浦バスケットボールスクール", "土浦")) },
  "ibaraki/tsukuba": { name: "つくば市", prefName: "茨城県", prefSlug: "ibaraki", schools: areaSchools("つくば市", "茨城県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("つくばバスケットボールスクール", "つくば")) },
  // ── 石川県 ──
  "ishikawa/kanazawa": { name: "金沢市", prefName: "石川県", prefSlug: "ishikawa", schools: areaSchools("金沢市", "石川県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("金沢バスケットボールスクール", "金沢")) },
  "ishikawa/nonoichi": { name: "野々市市", prefName: "石川県", prefSlug: "ishikawa", schools: areaSchools("野々市市", "石川県", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("野々市バスケットボールスクール", "野々市")) },
  "ishikawa/uchinada": { name: "内灘町", prefName: "石川県", prefSlug: "ishikawa", schools: areaSchools("内灘町", "石川県", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("内灘バスケットボールスクール", "内灘")) },
  // ── 神奈川県 ──
  "kanagawa/aoba": { name: "青葉区", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("青葉区", "神奈川県", DREAM_COURT, localSchool("川崎ブレイブサンダース バスケットボールスクール 青葉", "青葉区", "Bリーグ・川崎ブレイブサンダースが運営。青葉区エリアでの本格指導。", 7150, 4.6), SPORTS_DEPOT, MINI_BASKET) },
  "kanagawa/atsugi": { name: "厚木市", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("厚木市", "神奈川県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("厚木バスケットボールスクール", "厚木")) },
  "kanagawa/ebina": { name: "海老名市", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("海老名市", "神奈川県", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("海老名バスケットボールスクール", "海老名")) },
  "kanagawa/fujisawa": { name: "藤沢市", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("藤沢市", "神奈川県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("藤沢バスケットボールスクール", "藤沢")) },
  "kanagawa/kohoku": { name: "港北区", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("港北区", "神奈川県", DREAM_COURT, localSchool("川崎ブレイブサンダース バスケットボールスクール 港北", "港北区", "Bリーグ・川崎ブレイブサンダース関連。港北エリアでプロ水準の指導。", 7150, 4.6), SPORTS_DEPOT, MINI_BASKET) },
  "kanagawa/midori": { name: "緑区", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("緑区", "神奈川県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("緑区バスケットボールスクール", "緑区")) },
  "kanagawa/nakahara": { name: "中原区", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("中原区", "神奈川県", localSchool("川崎ブレイブサンダース バスケットボールスクール 中原", "中原区", "Bリーグ・川崎ブレイブサンダースのホームエリアに近い直営スクール。", 7150, 4.7), DREAM_COURT, SPORTS_DEPOT, MINI_BASKET) },
  "kanagawa/nakahara-shinjou": { name: "中原区（新城）", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("新城", "神奈川県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("新城バスケットボールスクール", "新城")) },
  "kanagawa/sagamihara": { name: "相模原市", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("相模原市", "神奈川県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("相模原バスケットボールスクール", "相模原")) },
  "kanagawa/takatsu": { name: "高津区", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("高津区", "神奈川県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("高津バスケットボールスクール", "高津")) },
  "kanagawa/tsuzuki": { name: "都筑区", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("都筑区", "神奈川県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("都筑バスケットボールスクール", "都筑")) },
  "kanagawa/yamato": { name: "大和市", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("大和市", "神奈川県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("大和バスケットボールスクール", "大和")) },
  "kanagawa/yokosuka": { name: "横須賀市", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("横須賀市", "神奈川県", SPORTS_DEPOT, DREAM_COURT, MINI_BASKET, localSchool("横須賀バスケットボールスクール", "横須賀")) },
  "kanagawa/zushi": { name: "逗子市", prefName: "神奈川県", prefSlug: "kanagawa", schools: areaSchools("逗子市", "神奈川県", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("逗子バスケットボールスクール", "逗子")) },
  // ── 京都府 ──
  "kyoto/kyoto-city": { name: "京都市", prefName: "京都府", prefSlug: "kyoto", schools: areaSchools("京都市", "京都府", localSchool("京都ハンナリーズ バスケットボールスクール", "京都市", "Bリーグ・京都ハンナリーズ関連スクール。プロの指導メソッドで基礎から本格指導。", 6600, 4.5), DREAM_COURT, SPORTS_DEPOT, MINI_BASKET) },
  // ── 長野県 ──
  "nagano/nagano-city": { name: "長野市", prefName: "長野県", prefSlug: "nagano", schools: areaSchools("長野市", "長野県", localSchool("信州ブレイブウォリアーズ バスケットボールスクール", "長野市", "Bリーグ・信州ブレイブウォリアーズ関連スクール。地域密着型の本格指導。", 5500, 4.4), SPORTS_DEPOT, MINI_BASKET, DREAM_COURT) },
  // ── 埼玉県 ──
  "saitama/kawaguchi": { name: "川口市", prefName: "埼玉県", prefSlug: "saitama", schools: areaSchools("川口市", "埼玉県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("川口バスケットボールスクール", "川口")) },
  "saitama/koshigaya": { name: "越谷市", prefName: "埼玉県", prefSlug: "saitama", schools: areaSchools("越谷市", "埼玉県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("越谷バスケットボールスクール", "越谷")) },
  "saitama/minami": { name: "南区", prefName: "埼玉県", prefSlug: "saitama", schools: areaSchools("南区", "埼玉県", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("南区バスケットボールスクール", "南区")) },
  "saitama/urawa": { name: "浦和区", prefName: "埼玉県", prefSlug: "saitama", schools: areaSchools("浦和区", "埼玉県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("浦和バスケットボールスクール", "浦和")) },
  // ── 滋賀県 ──
  "shiga/kusatsu": { name: "草津市", prefName: "滋賀県", prefSlug: "shiga", schools: areaSchools("草津市", "滋賀県", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("草津バスケットボールスクール", "草津")) },
  "shiga/otsu": { name: "大津市", prefName: "滋賀県", prefSlug: "shiga", schools: areaSchools("大津市", "滋賀県", localSchool("滋賀レイクス バスケットボールスクール 大津", "大津市", "Bリーグ・滋賀レイクス関連スクール。大津エリアでのプロ連携指導。", 5500, 4.4), DREAM_COURT, SPORTS_DEPOT, MINI_BASKET) },
  // ── 東京都 ──
  "tokyo/chofu": { name: "調布市", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("調布市", "東京都", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("調布バスケットボールスクール", "調布")) },
  "tokyo/edogawa": { name: "江戸川区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("江戸川区", "東京都", SPORTS_DEPOT, DREAM_COURT, MINI_BASKET, localSchool("江戸川バスケットボールスクール", "江戸川")) },
  "tokyo/kita": { name: "北区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("北区", "東京都", MINI_BASKET, SPORTS_DEPOT, DREAM_COURT, localSchool("北区バスケットボールスクール", "北区")) },
  "tokyo/machida": { name: "町田市", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("町田市", "東京都", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("町田バスケットボールスクール", "町田")) },
  "tokyo/meguro": { name: "目黒区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("目黒区", "東京都", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("目黒バスケットボールスクール", "目黒")) },
  "tokyo/minato": { name: "港区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("港区", "東京都", localSchool("東京バスケットボールアカデミー 港区", "港区", "元プロ選手コーチによる本格指導。港区の充実した施設でバスケの基礎を習得。", 7700, 4.6), DREAM_COURT, SPORTS_DEPOT, MINI_BASKET) },
  "tokyo/nerima": { name: "練馬区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("練馬区", "東京都", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("練馬バスケットボールスクール", "練馬")) },
  "tokyo/setagaya": { name: "世田谷区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("世田谷区", "東京都", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("世田谷バスケットボールスクール", "世田谷")) },
  "tokyo/shibuya": { name: "渋谷区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("渋谷区", "東京都", localSchool("東京バスケットボールアカデミー 渋谷", "渋谷区", "渋谷エリアの本格バスケットボール教室。少人数制で丁寧な指導を提供。", 7700, 4.5), DREAM_COURT, SPORTS_DEPOT, MINI_BASKET) },
  "tokyo/shinagawa": { name: "品川区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("品川区", "東京都", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("品川バスケットボールスクール", "品川")) },
  "tokyo/shinjuku": { name: "新宿区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("新宿区", "東京都", DREAM_COURT, SPORTS_DEPOT, MINI_BASKET, localSchool("新宿バスケットボールスクール", "新宿")) },
  "tokyo/suginami": { name: "杉並区", prefName: "東京都", prefSlug: "tokyo", schools: areaSchools("杉並区", "東京都", SPORTS_DEPOT, DREAM_COURT, MINI_BASKET, localSchool("杉並バスケットボールスクール", "杉並")) },
  // ── 和歌山県 ──
  "wakayama/wakayama-city": { name: "和歌山市", prefName: "和歌山県", prefSlug: "wakayama", schools: areaSchools("和歌山市", "和歌山県", SPORTS_DEPOT, MINI_BASKET, DREAM_COURT, localSchool("和歌山バスケットボールスクール", "和歌山")) },
};

export const ALL_PREFS_LIST = [
  { slug: "osaka", name: "大阪府" }, { slug: "tokyo", name: "東京都" },
  { slug: "kanagawa", name: "神奈川県" }, { slug: "aichi", name: "愛知県" },
  { slug: "gifu", name: "岐阜県" }, { slug: "hyogo", name: "兵庫県" },
  { slug: "ibaraki", name: "茨城県" }, { slug: "ishikawa", name: "石川県" },
  { slug: "kyoto", name: "京都府" }, { slug: "nagano", name: "長野県" },
  { slug: "shiga", name: "滋賀県" }, { slug: "wakayama", name: "和歌山県" },
  { slug: "saitama", name: "埼玉県" }, { slug: "chiba", name: "千葉県" },
  { slug: "fukuoka", name: "福岡県" }, { slug: "hokkaido", name: "北海道" },
  { slug: "miyagi", name: "宮城県" }, { slug: "hiroshima", name: "広島県" },
  { slug: "shizuoka", name: "静岡県" }, { slug: "okayama", name: "岡山県" },
  { slug: "niigata", name: "新潟県" }, { slug: "tochigi", name: "栃木県" },
  { slug: "gunma", name: "群馬県" }, { slug: "mie", name: "三重県" },
  { slug: "nara", name: "奈良県" }, { slug: "fukui", name: "福井県" },
  { slug: "toyama", name: "富山県" }, { slug: "yamanashi", name: "山梨県" },
  { slug: "tottori", name: "鳥取県" }, { slug: "shimane", name: "島根県" },
  { slug: "kochi", name: "高知県" }, { slug: "tokushima", name: "徳島県" },
  { slug: "kagawa", name: "香川県" }, { slug: "saga", name: "佐賀県" },
  { slug: "oita", name: "大分県" }, { slug: "miyazaki", name: "宮崎県" },
  { slug: "okinawa", name: "沖縄県" }, { slug: "kumamoto", name: "熊本県" },
  { slug: "kagoshima", name: "鹿児島県" }, { slug: "nagasaki", name: "長崎県" },
  { slug: "ehime", name: "愛媛県" }, { slug: "yamaguchi", name: "山口県" },
  { slug: "fukushima", name: "福島県" }, { slug: "akita", name: "秋田県" },
  { slug: "yamagata", name: "山形県" }, { slug: "iwate", name: "岩手県" },
  { slug: "aomori", name: "青森県" },
];

export const STD_BLOGS_EXPORT = STD_BLOGS;
