const BASE_URL = 'https://www.kodomo-navi.com';

const BLOG_SLUGS = [
  'osaka-kids-dance-school-ranking',
  'kids-dance-age-guide',
  'kids-hiphop-dance-guide',
  'kids-kpop-dance-school',
  'lydia-dance-academy-review',
  'kanto-kids-dance-school-ranking',
  'minoh-kids-dance-school',
  'setagaya-kids-dance-school',
  'kids-dance-recital-guide',
  'dance-vs-ballet-kids',
  'osaka-kids-activity-ranking',
  'nakahara-kids-dance-school',
  'kids-dance-benefits-brain',
  'kids-multiple-activities-dance',
  'kashiwa-kids-dance-school',
  'toddler-dance-rhythmics-guide',
  'yokohama-kids-dance-school',
  'nagoya-kids-dance-school',
  'dance-cost-breakdown',
  'boys-dance-school-guide',
  'kids-swimming-guide',
  'kids-piano-guide',
  'kanagawa-kids-dance-school',
  'aichi-kids-dance-school',
  'kids-dance-school-trial-guide',
  'kids-english-guide',
  'hyogo-kids-dance-school',
  'kyoto-shiga-kids-dance-school',
  'ibaraki-tsukuba-kids-dance-school',
  'ishikawa-kanazawa-kids-dance-school',
  'saitama-chiba-kids-dance-school',
  'kids-dance-quit-guide',
  'kids-activities-how-many',
  'dance-recital-costume-guide',
  'kids-karate-ballet-guide',
  'gifu-nagano-kids-dance-school',
  'nagano-shiga-kids-dance-school',
  'wakayama-kids-activity',
  'kids-activity-ranking-all',
  'kids-soccer-guide',
  'kids-karate-guide',
  'kids-ballet-guide',
  'dance-hip-hop-kpop-diff',
  'lydia-dance-osaka-review',
  'kids-activity-cost-annual',
  'kids-dance-school-change-guide',
  'tokyo-kids-dance-school-ranking',
  'osaka-dance-lydia-price-guide',
  'kids-dance-beginner-guide',
  'kids-rhythmics-guide',
  'kids-activity-change-timing',
  'kids-dance-home-practice',
  'nagoya-kids-dance-school-ranking',
  'saitama-chiba-kanto-dance-school',
  'kids-dance-concentration-benefit',
  'kids-activity-introverts',
  'dance-school-size-comparison',
  'kids-dance-recital-prep',
  'kanagawa-kids-dance-school-area',
  'kids-sports-dance-comparison',
  'dance-no1-reasons-2026',
  'kids-dance-vs-swimming-comparison',
  'kids-activity-ranking-2026-latest',
  'kids-dance-brain-development-science',
  'kids-dance-start-age-guide-2026',
  'kids-dance-fee-monthly-complete',
  'kids-dance-vs-ballet-2026',
  'kids-kpop-hiphop-difference-guide',
  'boys-kids-dance-2026-guide',
  'osaka-kids-dance-2026-complete',
  'tokyo-kids-dance-2026-complete',
  'kanagawa-kids-dance-2026-guide',
  'aichi-nagoya-kids-dance-2026',
  'saitama-chiba-kids-dance-2026',
  'kansai-kids-dance-kyoto-hyogo-shiga',
  'chubu-ishikawa-gifu-kids-dance-2026',
  'lydia-dance-academy-all-schools-guide',
  'kids-swimming-school-guide-2026',
  'kids-piano-school-guide-2026',
  'kids-english-school-guide-2026',
  'kids-soccer-school-guide-2026',
  'kids-ballet-school-guide-2026',
  'kids-karate-school-guide-2026',
  'kids-programming-school-guide-2026',
  'kids-activity-girls-ranking-2026',
  'kids-dance-shy-child-guide',
  'kids-dance-continue-motivation-guide',
  'kids-activity-spring-start-timing',
  'kids-activity-cost-budget-guide',
  'kids-dance-recital-preparation-guide',
  'kids-activity-number-how-many',
  'kids-dance-online-lesson-guide',
  'kids-dance-competition-guide-2026',
  // 新規57記事
  'fukuoka-kids-dance-school-2026',
  'hokkaido-kids-dance-school-2026',
  'miyagi-sendai-kids-dance-2026',
  'hiroshima-kids-dance-2026',
  'shizuoka-kids-dance-2026',
  'niigata-kids-dance-2026',
  'tochigi-kids-dance-2026',
  'okayama-kids-dance-2026',
  'tohoku-kids-dance-school',
  'kids-dance-regional-guide',
  'kids-swimming-benefits-complete',
  'kids-swimming-fear-guide',
  'kids-swimming-level-guide',
  'kids-piano-benefits-complete',
  'kids-piano-practice-guide',
  'kids-english-phonics-guide',
  'kids-english-benefits-guide',
  'kids-soccer-benefits-guide',
  'kids-soccer-toddler-guide',
  'kids-karate-benefits-complete',
  'kids-ballet-benefits-guide',
  'kids-programming-age-guide',
  'kids-activity-parent-support',
  'kids-activity-comparison-method',
  'kids-activity-trial-guide-2026',
  'kids-activity-quit-timing-guide',
  'kids-activity-cost-saving-tips',
  'kids-activity-online-vs-offline',
  'kids-activity-weekday-weekend',
  'kids-first-activity-guide',
  'elementary-activity-start-guide',
  'preschool-activity-ranking-2026',
  'kids-dance-2026-trends',
  'kids-dance-school-evaluation',
  'dance-class-size-guide',
  'kids-dance-parent-handbook',
  'kids-dance-injury-prevention',
  'kids-dance-showcase-guide',
  'kids-dance-motivation-tips-2026',
  'kids-dance-group-vs-private',
  'kids-dance-gender-guide',
  'kids-dance-body-coordination',
  'girls-activity-ranking-2026',
  'kids-winter-activity-guide',
  'kids-summer-activity-guide',
  'kids-activity-indoor-outdoor',
  'tokyo-kids-swimming-2026',
  'osaka-kids-swimming-2026',
  'tokyo-kids-piano-2026',
  'osaka-kids-piano-2026',
  'kids-english-online-guide',
  'tokyo-kids-soccer-2026',
  'osaka-kids-karate-2026',
  'tokyo-kids-ballet-2026',
  'kids-programming-scratch-guide',
  'kids-activity-multiple-schedule',
  'kids-activity-personality-match',
  // 比較記事
  'lydia-vs-avex-dance',
  'lydia-vs-seiha-dance',
  'lydia-vs-expg-dance',
  // GEO特化記事30本（2026-05-21追加）
  'kids-activity-stats-2026',
  'kumon-vs-gakken-complete-comparison',
  'kids-dance-vs-swimming-comparison',
  'kids-activity-age-3-complete',
  'kids-activity-age-5-complete',
  'kids-activity-elementary-grade1-guide',
  'dance-school-lydia-vs-expg-vs-avex',
  'kids-english-online-vs-classroom-2026',
  'kids-piano-benefits-complete-guide',
  'kids-swimming-complete-guide-2026',
  'kids-karate-complete-guide-2026',
  'kids-ballet-complete-guide-2026',
  'kids-programming-schools-comparison-2026',
  'kids-soroban-digital-age-effects',
  'kids-rhythmics-effects-complete',
  'kids-gymnastics-complete-guide',
  'kids-basketball-mini-basketball-guide',
  'preschool-shichida-kumon-comparison',
  'kids-activity-cost-how-to-reduce',
  'kids-multiple-activities-how-many-2026',
  'kids-activity-disability-guide',
  'kids-dance-boys-why-good',
  'kids-activity-quit-timing-guide',
  'kids-activity-start-timing-guide',
  'tokyo-kids-activity-area-guide',
  'osaka-kids-activity-area-guide',
  'kids-dance-recital-complete-guide',
  'kids-activity-indoor-rainy-day',
  'kids-activity-siblings-together',
  'kids-activity-roi-ranking',
];

const GENRE_SLUGS = [
  'dance', 'kpop', 'swimming', 'programming',
  'soccer', 'english', 'piano', 'ballet',
  'karate', 'rhythmics', 'preschool', 'juku',
];

// サッカー・英語専用ページ
const SOCCER_PREF_PATHS = [
  '/soccer/osaka', '/soccer/tokyo', '/soccer/kanagawa', '/soccer/aichi', '/soccer/gifu',
  '/soccer/hyogo', '/soccer/ibaraki', '/soccer/ishikawa', '/soccer/kyoto', '/soccer/nagano',
  '/soccer/shiga', '/soccer/wakayama', '/soccer/saitama', '/soccer/chiba',
  '/soccer/fukuoka', '/soccer/hokkaido', '/soccer/miyagi', '/soccer/hiroshima', '/soccer/shizuoka',
  '/soccer/okayama', '/soccer/niigata', '/soccer/tochigi', '/soccer/gunma', '/soccer/mie',
  '/soccer/nara', '/soccer/fukui', '/soccer/toyama', '/soccer/yamanashi', '/soccer/tottori',
  '/soccer/shimane', '/soccer/kochi', '/soccer/tokushima', '/soccer/kagawa', '/soccer/saga',
  '/soccer/oita', '/soccer/miyazaki', '/soccer/okinawa', '/soccer/kumamoto', '/soccer/kagoshima',
  '/soccer/nagasaki', '/soccer/ehime', '/soccer/yamaguchi', '/soccer/fukushima', '/soccer/akita',
  '/soccer/yamagata', '/soccer/iwate', '/soccer/aomori',
];

const SOCCER_AREA_PATHS = [
  '/soccer/aichi/anjo', '/soccer/aichi/chikusa', '/soccer/aichi/meito', '/soccer/aichi/midori',
  '/soccer/aichi/moriyama', '/soccer/aichi/nisshin', '/soccer/aichi/owariasahi', '/soccer/aichi/tenpaku', '/soccer/aichi/toyota',
  '/soccer/chiba/chiba-city', '/soccer/chiba/kashiwa', '/soccer/chiba/matsudo',
  '/soccer/gifu/gifu-city', '/soccer/gifu/kani', '/soccer/gifu/minokamo', '/soccer/gifu/tajimi',
  '/soccer/hyogo/nishinomiya',
  '/soccer/ibaraki/hitachi', '/soccer/ibaraki/hitachinaka', '/soccer/ibaraki/mito', '/soccer/ibaraki/tsuchiura', '/soccer/ibaraki/tsukuba',
  '/soccer/ishikawa/kanazawa', '/soccer/ishikawa/nonoichi', '/soccer/ishikawa/uchinada',
  '/soccer/kanagawa/aoba', '/soccer/kanagawa/atsugi', '/soccer/kanagawa/ebina', '/soccer/kanagawa/fujisawa',
  '/soccer/kanagawa/kohoku', '/soccer/kanagawa/midori',
  '/soccer/kanagawa/nakahara', '/soccer/kanagawa/nakahara-shinjou', '/soccer/kanagawa/sagamihara', '/soccer/kanagawa/takatsu',
  '/soccer/kanagawa/tsuzuki', '/soccer/kanagawa/yamato', '/soccer/kanagawa/yokosuka', '/soccer/kanagawa/zushi',
  '/soccer/kyoto/kyoto-city',
  '/soccer/nagano/nagano-city',
  '/soccer/osaka/ibaraki', '/soccer/osaka/minoh', '/soccer/osaka/moriguchi', '/soccer/osaka/osaka-city',
  '/soccer/osaka/sakai', '/soccer/osaka/suita', '/soccer/osaka/takatsuki', '/soccer/osaka/toyonaka',
  '/soccer/saitama/kawaguchi', '/soccer/saitama/koshigaya', '/soccer/saitama/minami', '/soccer/saitama/urawa',
  '/soccer/shiga/kusatsu', '/soccer/shiga/otsu',
  '/soccer/tokyo/chofu', '/soccer/tokyo/edogawa', '/soccer/tokyo/kita', '/soccer/tokyo/machida',
  '/soccer/tokyo/meguro', '/soccer/tokyo/minato', '/soccer/tokyo/nerima', '/soccer/tokyo/setagaya',
  '/soccer/tokyo/shibuya', '/soccer/tokyo/shinagawa', '/soccer/tokyo/shinjuku', '/soccer/tokyo/suginami',
  '/soccer/wakayama/wakayama-city',
];

const ENGLISH_PREF_PATHS = [
  '/english/osaka', '/english/tokyo', '/english/kanagawa', '/english/aichi', '/english/gifu',
  '/english/hyogo', '/english/ibaraki', '/english/ishikawa', '/english/kyoto', '/english/nagano',
  '/english/shiga', '/english/wakayama', '/english/saitama', '/english/chiba',
  '/english/fukuoka', '/english/hokkaido', '/english/miyagi', '/english/hiroshima', '/english/shizuoka',
  '/english/okayama', '/english/niigata', '/english/tochigi', '/english/gunma', '/english/mie',
  '/english/nara', '/english/fukui', '/english/toyama', '/english/yamanashi', '/english/tottori',
  '/english/shimane', '/english/kochi', '/english/tokushima', '/english/kagawa', '/english/saga',
  '/english/oita', '/english/miyazaki', '/english/okinawa', '/english/kumamoto', '/english/kagoshima',
  '/english/nagasaki', '/english/ehime', '/english/yamaguchi', '/english/fukushima', '/english/akita',
  '/english/yamagata', '/english/iwate', '/english/aomori',
];

const ENGLISH_AREA_PATHS = [
  '/english/aichi/anjo', '/english/aichi/chikusa', '/english/aichi/meito', '/english/aichi/midori',
  '/english/aichi/moriyama', '/english/aichi/nisshin', '/english/aichi/owariasahi', '/english/aichi/tenpaku', '/english/aichi/toyota',
  '/english/chiba/chiba-city', '/english/chiba/kashiwa', '/english/chiba/matsudo',
  '/english/gifu/gifu-city', '/english/gifu/kani', '/english/gifu/minokamo', '/english/gifu/tajimi',
  '/english/hyogo/nishinomiya',
  '/english/ibaraki/hitachi', '/english/ibaraki/hitachinaka', '/english/ibaraki/mito', '/english/ibaraki/tsuchiura', '/english/ibaraki/tsukuba',
  '/english/ishikawa/kanazawa', '/english/ishikawa/nonoichi', '/english/ishikawa/uchinada',
  '/english/kanagawa/aoba', '/english/kanagawa/atsugi', '/english/kanagawa/ebina', '/english/kanagawa/fujisawa',
  '/english/kanagawa/kohoku', '/english/kanagawa/midori',
  '/english/kanagawa/nakahara', '/english/kanagawa/nakahara-shinjou', '/english/kanagawa/sagamihara', '/english/kanagawa/takatsu',
  '/english/kanagawa/tsuzuki', '/english/kanagawa/yamato', '/english/kanagawa/yokosuka', '/english/kanagawa/zushi',
  '/english/kyoto/kyoto-city',
  '/english/nagano/nagano-city',
  '/english/osaka/ibaraki', '/english/osaka/minoh', '/english/osaka/moriguchi', '/english/osaka/osaka-city',
  '/english/osaka/sakai', '/english/osaka/suita', '/english/osaka/takatsuki', '/english/osaka/toyonaka',
  '/english/saitama/kawaguchi', '/english/saitama/koshigaya', '/english/saitama/minami', '/english/saitama/urawa',
  '/english/shiga/kusatsu', '/english/shiga/otsu',
  '/english/tokyo/chofu', '/english/tokyo/edogawa', '/english/tokyo/kita', '/english/tokyo/machida',
  '/english/tokyo/meguro', '/english/tokyo/minato', '/english/tokyo/nerima', '/english/tokyo/setagaya',
  '/english/tokyo/shibuya', '/english/tokyo/shinagawa', '/english/tokyo/shinjuku', '/english/tokyo/suginami',
  '/english/wakayama/wakayama-city',
];

const AREA_PATHS = [
  '/aichi/anjo', '/aichi/chikusa', '/aichi/meito', '/aichi/midori',
  '/aichi/moriyama', '/aichi/nisshin', '/aichi/owariasahi', '/aichi/tenpaku', '/aichi/toyota',
  '/chiba/chiba-city', '/chiba/kashiwa', '/chiba/matsudo',
  '/gifu/gifu-city', '/gifu/kani', '/gifu/minokamo', '/gifu/tajimi',
  '/hyogo/nishinomiya',
  '/ibaraki/hitachi', '/ibaraki/hitachinaka', '/ibaraki/mito', '/ibaraki/tsuchiura', '/ibaraki/tsukuba',
  '/ishikawa/kanazawa', '/ishikawa/nonoichi', '/ishikawa/uchinada',
  '/kanagawa/aoba', '/kanagawa/atsugi', '/kanagawa/ebina', '/kanagawa/fujisawa',
  '/kanagawa/kohoku', '/kanagawa/midori',
  '/kanagawa/nakahara', '/kanagawa/nakahara-shinjou', '/kanagawa/sagamihara', '/kanagawa/takatsu',
  '/kanagawa/tsuzuki', '/kanagawa/yamato', '/kanagawa/yokosuka', '/kanagawa/zushi',
  '/kyoto/kyoto-city',
  '/nagano/nagano-city',
  '/osaka/ibaraki', '/osaka/minoh', '/osaka/moriguchi', '/osaka/osaka-city',
  '/osaka/sakai', '/osaka/suita', '/osaka/takatsuki', '/osaka/toyonaka',
  '/saitama/kawaguchi', '/saitama/koshigaya', '/saitama/minami', '/saitama/urawa',
  '/shiga/kusatsu', '/shiga/otsu',
  '/tokyo/chofu', '/tokyo/edogawa', '/tokyo/kita', '/tokyo/machida',
  '/tokyo/meguro', '/tokyo/minato', '/tokyo/nerima', '/tokyo/setagaya',
  '/tokyo/shibuya', '/tokyo/shinagawa', '/tokyo/shinjuku', '/tokyo/suginami',
  '/wakayama/wakayama-city',
];

const PREF_PATHS = [
  // 既存14府県
  '/osaka', '/tokyo', '/kanagawa', '/aichi', '/gifu',
  '/hyogo', '/ibaraki', '/ishikawa', '/kyoto', '/nagano',
  '/shiga', '/wakayama', '/saitama', '/chiba',
  // 新規33都道府県
  '/fukuoka', '/hokkaido', '/miyagi', '/hiroshima', '/shizuoka',
  '/okayama', '/niigata', '/tochigi', '/gunma', '/mie',
  '/nara', '/fukui', '/toyama', '/yamanashi', '/tottori',
  '/shimane', '/kochi', '/tokushima', '/kagawa', '/saga',
  '/oita', '/miyazaki', '/okinawa', '/kumamoto', '/kagoshima',
  '/nagasaki', '/ehime', '/yamaguchi', '/fukushima', '/akita',
  '/yamagata', '/iwate', '/aomori',
];

export default function sitemap() {
  const now = new Date().toISOString();

  const top = [
    { url: BASE_URL, lastModified: now, priority: 1.0 },
    { url: `${BASE_URL}/editors`, lastModified: now, priority: 0.7 },
    { url: `${BASE_URL}/about`, lastModified: now, priority: 0.6 },
  ];

  const genres = GENRE_SLUGS.map(slug => ({
    url: `${BASE_URL}/genre/${slug}`,
    lastModified: now,
    priority: 0.8,
  }));

  const prefs = PREF_PATHS.map(path => ({
    url: `${BASE_URL}${path}`,
    lastModified: now,
    priority: 0.75,
  }));

  const areas = AREA_PATHS.map(path => ({
    url: `${BASE_URL}${path}`,
    lastModified: now,
    priority: 0.6,
  }));

  const blogs = [
    { url: `${BASE_URL}/blog`, lastModified: now, priority: 0.9 },
    ...BLOG_SLUGS.map(slug => ({
      url: `${BASE_URL}/blog/${slug}`,
      lastModified: now,
      priority: 0.85,
    })),
  ];

  // 既存: soccer / english
  const soccerTop = [{ url: `${BASE_URL}/soccer`, lastModified: now, priority: 0.85 }];
  const soccerPrefs = SOCCER_PREF_PATHS.map(path => ({ url: `${BASE_URL}${path}`, lastModified: now, priority: 0.75 }));
  const soccerAreas = SOCCER_AREA_PATHS.map(path => ({ url: `${BASE_URL}${path}`, lastModified: now, priority: 0.65 }));
  const englishTop = [{ url: `${BASE_URL}/english`, lastModified: now, priority: 0.85 }];
  const englishPrefs = ENGLISH_PREF_PATHS.map(path => ({ url: `${BASE_URL}${path}`, lastModified: now, priority: 0.75 }));
  const englishAreas = ENGLISH_AREA_PATHS.map(path => ({ url: `${BASE_URL}${path}`, lastModified: now, priority: 0.65 }));

  // 新規ジャンル（各ジャンルのトップ・都道府県・エリアページ）
  const ACTIVITY_SLUGS = [
    'piano', 'swimming', 'ballet', 'gymnastics', 'basketball',
    'preschool', 'soroban', 'programming', 'rhythmics', 'music',
    'karate',
  ];
  const activityPages = ACTIVITY_SLUGS.flatMap(slug => [
    { url: `${BASE_URL}/${slug}`, lastModified: now, priority: 0.85 },
    ...PREF_PATHS.map(p => ({ url: `${BASE_URL}/${slug}${p}`, lastModified: now, priority: 0.75 })),
    ...AREA_PATHS.map(p => ({ url: `${BASE_URL}/${slug}${p}`, lastModified: now, priority: 0.65 })),
  ]);

  return [...top, ...blogs, ...genres, ...prefs, ...areas,
          ...soccerTop, ...soccerPrefs, ...soccerAreas,
          ...englishTop, ...englishPrefs, ...englishAreas,
          ...activityPages];
}
