// /app/dance/danceData.js

const LYDIA = {
  name: "リディアダンスアカデミー",
  rating: 4.8, fee: 7700, age: "3歳〜15歳",
  featured: true,
  trialUrl: "https://re-dia.jp/contact",
  url: "https://re-dia.jp/",
  desc: "全国100校以上展開のキッズダンススクール。現役プロダンサー講師200名以上在籍。3歳のリトルクラスから本格コースまで充実。ヒップホップ・ジャズ・K-POPなど多ジャンル対応。発表会・コンクールも充実。",
  color: "#E53935", emoji: "🏆",
  tags: ["全国100校以上", "初回体験無料", "3歳〜OK", "プロ講師200名+", "多ジャンル対応", "発表会充実"]
};

const EXPG = {
  name: "EXPG DANCE & VOCAL STUDIO",
  rating: 4.5, fee: 12100, age: "3歳〜",
  url: "https://expg.jp/",
  desc: "LDH系列のダンス・ボーカルスクール。プロを目指す本格派向け。月謝高めだが指導レベルは高い。",
  color: "#1A1A1A", emoji: "⭐",
  tags: ["LDH系列", "プロ志向", "ボーカルも学べる"]
};

const AVEX = {
  name: "エイベックス・ダンスマスター",
  rating: 4.4, fee: 11000, age: "年中〜高校生",
  url: "https://dancemaster.avex.jp/",
  desc: "エイベックス直営のキッズダンススクール。初心者が楽しめる環境を重視。ショッピングモール内が多く通いやすい。",
  color: "#1B2A4A", emoji: "💫",
  tags: ["エイベックス直営", "初心者歓迎", "ショッピングモール内"]
};

const BDC = {
  name: "ブレスダンスカンパニー",
  rating: 4.3, fee: 8800, age: "3歳〜",
  url: "https://www.bdc.jp/",
  desc: "全国展開のダンススクール。ヒップホップ・K-POP・バレエなど幅広いジャンルに対応。初心者歓迎。",
  color: "#6A1B9A", emoji: "💜",
  tags: ["全国展開", "多ジャンル", "初心者OK"]
};

const STD_DANCE_FAQS = (prefName) => [
  { q: `${prefName}のダンス教室は何歳から通えますか？`, a: "リディアダンスアカデミーをはじめ、多くのスクールは3歳から通えます。リトルクラス・幼児コースを充実させているスクールが増えています。" },
  { q: `${prefName}のダンスの月謝相場は？`, a: "週1回で月6,000〜12,000円が一般的です。リディアダンスアカデミーは月7,700円〜で、初回体験無料です。" },
  { q: "女の子だけでなく男の子もダンスを習えますか？", a: "もちろんです。ヒップホップやブレイクダンスは男の子にも大人気です。性別問わず歓迎しているスクールがほとんどです。" },
  { q: "ダンスを習うとどんな効果がありますか？", a: "リズム感・柔軟性・集中力・協調性・表現力が身につきます。発表会を通じて自己肯定感も高まります。" },
];

const STD_DANCE_BLOGS = [
  { href: "/blog/kids-dance-age-guide", text: "子供ダンスは何歳から始める？完全ガイド" },
  { href: "/blog/osaka-kids-dance-school-ranking", text: "大阪キッズダンス教室おすすめランキング" },
  { href: "/blog/kids-hiphop-dance-guide", text: "子供ヒップホップダンス教室の選び方" },
  { href: "/blog/kids-kpop-dance-school", text: "子供K-POPダンス教室おすすめ" },
  { href: "/blog/lydia-dance-academy-review", text: "リディアダンスアカデミーの評判・口コミ" },
];

export const DANCE_PREFS = {
  osaka: {
    name: "大阪府",
    heroText: "関西最大都市・大阪の子どもダンス教室",
    areas: [
      { slug: "osaka-city", name: "大阪市" },
      { slug: "minoh", name: "箕面市" },
      { slug: "moriguchi", name: "守口市" },
      { slug: "sakai", name: "堺市" },
      { slug: "suita", name: "吹田市" },
      { slug: "takatsuki", name: "高槻市" },
      { slug: "toyonaka", name: "豊中市" },
      { slug: "ibaraki", name: "茨木市" },
    ],
    schools: [
      { ...LYDIA, desc: "全国100校以上展開のキッズダンススクール。牧落校・船場阪大前校など大阪各地に展開。現役プロダンサー講師200名以上在籍。3歳のリトルクラスから本格コースまで充実。ヒップホップ・ジャズ・K-POPなど多ジャンル対応。発表会・コンクールも充実。", tags: ["大阪府内多数展開", "初回体験無料", "3歳〜OK", "プロ講師200名+", "多ジャンル対応", "発表会充実"] },
      EXPG, AVEX, BDC
    ],
    faqs: STD_DANCE_FAQS("大阪府"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "kanagawa", name: "神奈川県" },
      { slug: "aichi", name: "愛知県" }, { slug: "kyoto", name: "京都府" },
      { slug: "hyogo", name: "兵庫県" },
    ],
  },
  tokyo: {
    name: "東京都",
    heroText: "首都・東京の子ども向けダンス教室",
    areas: [
      { slug: "chofu", name: "調布市" }, { slug: "edogawa", name: "江戸川区" },
      { slug: "kita", name: "北区" }, { slug: "machida", name: "町田市" },
      { slug: "meguro", name: "目黒区" }, { slug: "minato", name: "港区" },
      { slug: "nerima", name: "練馬区" }, { slug: "setagaya", name: "世田谷区" },
      { slug: "shibuya", name: "渋谷区" }, { slug: "shinagawa", name: "品川区" },
      { slug: "shinjuku", name: "新宿区" }, { slug: "suginami", name: "杉並区" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("東京都"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "kanagawa", name: "神奈川県" }, { slug: "saitama", name: "埼玉県" },
      { slug: "chiba", name: "千葉県" }, { slug: "osaka", name: "大阪府" },
    ],
  },
  kanagawa: {
    name: "神奈川県",
    heroText: "横浜・川崎を擁する神奈川県の子どもダンス教室",
    areas: [
      { slug: "aoba", name: "青葉区" }, { slug: "atsugi", name: "厚木市" },
      { slug: "ebina", name: "海老名市" }, { slug: "fujisawa", name: "藤沢市" },
      { slug: "kohoku", name: "港北区" }, { slug: "midori", name: "緑区" },
      { slug: "nakahara", name: "中原区" }, { slug: "nakahara-shinjou", name: "中原区（新城）" },
      { slug: "sagamihara", name: "相模原市" }, { slug: "takatsu", name: "高津区" },
      { slug: "tsuzuki", name: "都筑区" }, { slug: "yamato", name: "大和市" },
      { slug: "yokosuka", name: "横須賀市" }, { slug: "zushi", name: "逗子市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("神奈川県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "chiba", name: "千葉県" }, { slug: "shizuoka", name: "静岡県" },
    ],
  },
  aichi: {
    name: "愛知県",
    heroText: "名古屋を中心とした愛知県の子どもダンス教室",
    areas: [
      { slug: "anjo", name: "安城市" }, { slug: "chikusa", name: "千種区" },
      { slug: "meito", name: "名東区" }, { slug: "midori", name: "緑区" },
      { slug: "moriyama", name: "守山区" }, { slug: "nisshin", name: "日進市" },
      { slug: "owariasahi", name: "尾張旭市" }, { slug: "tenpaku", name: "天白区" },
      { slug: "toyota", name: "豊田市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("愛知県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "gifu", name: "岐阜県" },
      { slug: "shizuoka", name: "静岡県" }, { slug: "mie", name: "三重県" },
    ],
  },
  gifu: {
    name: "岐阜県",
    heroText: "岐阜県の子ども向けダンス教室",
    areas: [
      { slug: "gifu-city", name: "岐阜市" }, { slug: "kani", name: "可児市" },
      { slug: "minokamo", name: "美濃加茂市" }, { slug: "tajimi", name: "多治見市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("岐阜県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "aichi", name: "愛知県" }, { slug: "shizuoka", name: "静岡県" },
      { slug: "nagano", name: "長野県" }, { slug: "mie", name: "三重県" },
    ],
  },
  hyogo: {
    name: "兵庫県",
    heroText: "神戸・西宮を擁する兵庫県の子どもダンス教室",
    areas: [
      { slug: "nishinomiya", name: "西宮市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("兵庫県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "kyoto", name: "京都府" },
      { slug: "nara", name: "奈良県" }, { slug: "wakayama", name: "和歌山県" },
    ],
  },
  ibaraki: {
    name: "茨城県",
    heroText: "茨城県の子ども向けダンス教室",
    areas: [
      { slug: "hitachi", name: "日立市" }, { slug: "hitachinaka", name: "ひたちなか市" },
      { slug: "mito", name: "水戸市" }, { slug: "tsuchiura", name: "土浦市" },
      { slug: "tsukuba", name: "つくば市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("茨城県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "chiba", name: "千葉県" }, { slug: "tochigi", name: "栃木県" },
    ],
  },
  ishikawa: {
    name: "石川県",
    heroText: "金沢を中心とした石川県の子どもダンス教室",
    areas: [
      { slug: "kanazawa", name: "金沢市" }, { slug: "nonoichi", name: "野々市市" },
      { slug: "uchinada", name: "内灘町" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("石川県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "toyama", name: "富山県" }, { slug: "fukui", name: "福井県" },
      { slug: "niigata", name: "新潟県" }, { slug: "nagano", name: "長野県" },
    ],
  },
  kyoto: {
    name: "京都府",
    heroText: "古都・京都の子ども向けダンス教室",
    areas: [
      { slug: "kyoto-city", name: "京都市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("京都府"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "hyogo", name: "兵庫県" },
      { slug: "shiga", name: "滋賀県" }, { slug: "nara", name: "奈良県" },
    ],
  },
  nagano: {
    name: "長野県",
    heroText: "長野県の子ども向けダンス教室",
    areas: [
      { slug: "nagano-city", name: "長野市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("長野県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "aichi", name: "愛知県" },
      { slug: "gifu", name: "岐阜県" }, { slug: "niigata", name: "新潟県" },
    ],
  },
  shiga: {
    name: "滋賀県",
    heroText: "琵琶湖を擁する滋賀県の子どもダンス教室",
    areas: [
      { slug: "kusatsu", name: "草津市" }, { slug: "otsu", name: "大津市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("滋賀県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "kyoto", name: "京都府" },
      { slug: "hyogo", name: "兵庫県" }, { slug: "mie", name: "三重県" },
    ],
  },
  wakayama: {
    name: "和歌山県",
    heroText: "和歌山県の子ども向けダンス教室",
    areas: [
      { slug: "wakayama-city", name: "和歌山市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("和歌山県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "hyogo", name: "兵庫県" },
      { slug: "nara", name: "奈良県" }, { slug: "mie", name: "三重県" },
    ],
  },
  saitama: {
    name: "埼玉県",
    heroText: "埼玉県の子ども向けダンス教室",
    areas: [
      { slug: "kawaguchi", name: "川口市" }, { slug: "koshigaya", name: "越谷市" },
      { slug: "minami", name: "南区" }, { slug: "urawa", name: "浦和区" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("埼玉県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "kanagawa", name: "神奈川県" },
      { slug: "chiba", name: "千葉県" }, { slug: "gunma", name: "群馬県" },
    ],
  },
  chiba: {
    name: "千葉県",
    heroText: "千葉県の子ども向けダンス教室",
    areas: [
      { slug: "chiba-city", name: "千葉市" }, { slug: "kashiwa", name: "柏市" },
      { slug: "matsudo", name: "松戸市" },
    ],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("千葉県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "kanagawa", name: "神奈川県" }, { slug: "ibaraki", name: "茨城県" },
    ],
  },
  fukuoka: {
    name: "福岡県",
    heroText: "九州最大の都市・福岡の子どもダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("福岡県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "saga", name: "佐賀県" }, { slug: "nagasaki", name: "長崎県" },
      { slug: "kumamoto", name: "熊本県" }, { slug: "oita", name: "大分県" },
    ],
  },
  hokkaido: {
    name: "北海道",
    heroText: "北海道の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("北海道"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "aomori", name: "青森県" }, { slug: "iwate", name: "岩手県" },
      { slug: "miyagi", name: "宮城県" }, { slug: "akita", name: "秋田県" },
    ],
  },
  miyagi: {
    name: "宮城県",
    heroText: "仙台を擁する宮城県の子どもダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("宮城県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "fukushima", name: "福島県" }, { slug: "yamagata", name: "山形県" },
      { slug: "iwate", name: "岩手県" }, { slug: "akita", name: "秋田県" },
    ],
  },
  hiroshima: {
    name: "広島県",
    heroText: "広島県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("広島県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "okayama", name: "岡山県" }, { slug: "yamaguchi", name: "山口県" },
      { slug: "shimane", name: "島根県" }, { slug: "tottori", name: "鳥取県" },
    ],
  },
  shizuoka: {
    name: "静岡県",
    heroText: "静岡県の子どもダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("静岡県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "aichi", name: "愛知県" }, { slug: "kanagawa", name: "神奈川県" },
      { slug: "nagano", name: "長野県" }, { slug: "yamanashi", name: "山梨県" },
    ],
  },
  okayama: {
    name: "岡山県",
    heroText: "岡山県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("岡山県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "hiroshima", name: "広島県" }, { slug: "tottori", name: "鳥取県" },
      { slug: "hyogo", name: "兵庫県" }, { slug: "kagawa", name: "香川県" },
    ],
  },
  niigata: {
    name: "新潟県",
    heroText: "新潟県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("新潟県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "nagano", name: "長野県" }, { slug: "fukushima", name: "福島県" },
      { slug: "yamagata", name: "山形県" }, { slug: "toyama", name: "富山県" },
    ],
  },
  tochigi: {
    name: "栃木県",
    heroText: "栃木県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("栃木県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "gunma", name: "群馬県" }, { slug: "ibaraki", name: "茨城県" },
    ],
  },
  gunma: {
    name: "群馬県",
    heroText: "群馬県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("群馬県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "saitama", name: "埼玉県" },
      { slug: "tochigi", name: "栃木県" }, { slug: "nagano", name: "長野県" },
    ],
  },
  mie: {
    name: "三重県",
    heroText: "三重県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("三重県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "aichi", name: "愛知県" }, { slug: "osaka", name: "大阪府" },
      { slug: "kyoto", name: "京都府" }, { slug: "nara", name: "奈良県" },
    ],
  },
  nara: {
    name: "奈良県",
    heroText: "奈良県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("奈良県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "osaka", name: "大阪府" }, { slug: "kyoto", name: "京都府" },
      { slug: "hyogo", name: "兵庫県" }, { slug: "wakayama", name: "和歌山県" },
    ],
  },
  fukui: {
    name: "福井県",
    heroText: "福井県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("福井県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "ishikawa", name: "石川県" }, { slug: "toyama", name: "富山県" },
      { slug: "gifu", name: "岐阜県" }, { slug: "kyoto", name: "京都府" },
    ],
  },
  toyama: {
    name: "富山県",
    heroText: "富山県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("富山県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "ishikawa", name: "石川県" }, { slug: "fukui", name: "福井県" },
      { slug: "niigata", name: "新潟県" }, { slug: "nagano", name: "長野県" },
    ],
  },
  yamanashi: {
    name: "山梨県",
    heroText: "山梨県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("山梨県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokyo", name: "東京都" }, { slug: "kanagawa", name: "神奈川県" },
      { slug: "shizuoka", name: "静岡県" }, { slug: "nagano", name: "長野県" },
    ],
  },
  tottori: {
    name: "鳥取県",
    heroText: "鳥取県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("鳥取県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "shimane", name: "島根県" }, { slug: "okayama", name: "岡山県" },
      { slug: "hiroshima", name: "広島県" }, { slug: "hyogo", name: "兵庫県" },
    ],
  },
  shimane: {
    name: "島根県",
    heroText: "島根県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("島根県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tottori", name: "鳥取県" }, { slug: "hiroshima", name: "広島県" },
      { slug: "yamaguchi", name: "山口県" }, { slug: "okayama", name: "岡山県" },
    ],
  },
  kochi: {
    name: "高知県",
    heroText: "高知県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("高知県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokushima", name: "徳島県" }, { slug: "ehime", name: "愛媛県" },
      { slug: "kagawa", name: "香川県" }, { slug: "hiroshima", name: "広島県" },
    ],
  },
  tokushima: {
    name: "徳島県",
    heroText: "徳島県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("徳島県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "kagawa", name: "香川県" }, { slug: "ehime", name: "愛媛県" },
      { slug: "kochi", name: "高知県" }, { slug: "hyogo", name: "兵庫県" },
    ],
  },
  kagawa: {
    name: "香川県",
    heroText: "香川県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("香川県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "tokushima", name: "徳島県" }, { slug: "ehime", name: "愛媛県" },
      { slug: "kochi", name: "高知県" }, { slug: "okayama", name: "岡山県" },
    ],
  },
  saga: {
    name: "佐賀県",
    heroText: "佐賀県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("佐賀県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "nagasaki", name: "長崎県" },
      { slug: "kumamoto", name: "熊本県" }, { slug: "oita", name: "大分県" },
    ],
  },
  oita: {
    name: "大分県",
    heroText: "大分県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("大分県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "kumamoto", name: "熊本県" },
      { slug: "miyazaki", name: "宮崎県" }, { slug: "ehime", name: "愛媛県" },
    ],
  },
  miyazaki: {
    name: "宮崎県",
    heroText: "宮崎県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("宮崎県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "oita", name: "大分県" },
      { slug: "kumamoto", name: "熊本県" }, { slug: "kagoshima", name: "鹿児島県" },
    ],
  },
  okinawa: {
    name: "沖縄県",
    heroText: "沖縄県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("沖縄県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "kagoshima", name: "鹿児島県" }, { slug: "fukuoka", name: "福岡県" },
      { slug: "miyazaki", name: "宮崎県" }, { slug: "kumamoto", name: "熊本県" },
    ],
  },
  kumamoto: {
    name: "熊本県",
    heroText: "熊本県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("熊本県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "saga", name: "佐賀県" },
      { slug: "nagasaki", name: "長崎県" }, { slug: "oita", name: "大分県" },
    ],
  },
  kagoshima: {
    name: "鹿児島県",
    heroText: "鹿児島県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("鹿児島県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "kumamoto", name: "熊本県" },
      { slug: "miyazaki", name: "宮崎県" }, { slug: "okinawa", name: "沖縄県" },
    ],
  },
  nagasaki: {
    name: "長崎県",
    heroText: "長崎県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("長崎県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "fukuoka", name: "福岡県" }, { slug: "saga", name: "佐賀県" },
      { slug: "kumamoto", name: "熊本県" }, { slug: "oita", name: "大分県" },
    ],
  },
  ehime: {
    name: "愛媛県",
    heroText: "愛媛県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("愛媛県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "kagawa", name: "香川県" }, { slug: "tokushima", name: "徳島県" },
      { slug: "kochi", name: "高知県" }, { slug: "hiroshima", name: "広島県" },
    ],
  },
  yamaguchi: {
    name: "山口県",
    heroText: "山口県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("山口県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "hiroshima", name: "広島県" }, { slug: "shimane", name: "島根県" },
      { slug: "fukuoka", name: "福岡県" }, { slug: "tottori", name: "鳥取県" },
    ],
  },
  fukushima: {
    name: "福島県",
    heroText: "福島県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("福島県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "miyagi", name: "宮城県" }, { slug: "yamagata", name: "山形県" },
      { slug: "ibaraki", name: "茨城県" }, { slug: "niigata", name: "新潟県" },
    ],
  },
  akita: {
    name: "秋田県",
    heroText: "秋田県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("秋田県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "miyagi", name: "宮城県" }, { slug: "iwate", name: "岩手県" },
      { slug: "yamagata", name: "山形県" }, { slug: "aomori", name: "青森県" },
    ],
  },
  yamagata: {
    name: "山形県",
    heroText: "山形県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("山形県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "miyagi", name: "宮城県" }, { slug: "akita", name: "秋田県" },
      { slug: "fukushima", name: "福島県" }, { slug: "niigata", name: "新潟県" },
    ],
  },
  iwate: {
    name: "岩手県",
    heroText: "岩手県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("岩手県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "miyagi", name: "宮城県" }, { slug: "akita", name: "秋田県" },
      { slug: "aomori", name: "青森県" }, { slug: "fukushima", name: "福島県" },
    ],
  },
  aomori: {
    name: "青森県",
    heroText: "青森県の子ども向けダンス教室",
    areas: [],
    schools: [LYDIA, EXPG, AVEX, BDC],
    faqs: STD_DANCE_FAQS("青森県"),
    blogs: STD_DANCE_BLOGS,
    otherPrefs: [
      { slug: "iwate", name: "岩手県" }, { slug: "akita", name: "秋田県" },
      { slug: "miyagi", name: "宮城県" }, { slug: "hokkaido", name: "北海道" },
    ],
  },
};

// ────────────────────────────────────────────
// DANCE_AREAS: エリア別データ（SOCCER_AREASと同じキー構造）
// ────────────────────────────────────────────

function areaDanceSchools(areaName, prefName) {
  return [
    { ...LYDIA, desc: `${prefName}${areaName}エリアに対応。全国100校以上展開のキッズダンススクール。現役プロダンサー講師200名以上在籍。3歳のリトルクラスから本格コースまで充実。ヒップホップ・ジャズ・K-POPなど多ジャンル対応。発表会・コンクールも充実。` },
    { ...EXPG },
    { ...AVEX },
    { ...BDC },
  ];
}

export const DANCE_AREAS = {
  // ── 大阪府 ──
  "osaka/osaka-city": { name: "大阪市", prefName: "大阪府", prefSlug: "osaka",
    intro: "大阪市は梅田・難波・天王寺の三大ターミナルを中心に、Osaka MetroとJRが市内全域を結ぶ西日本最大の都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "Osaka Metro御堂筋線・谷町線やJR大阪環状線の駅周辺にスクールが点在し、都島・京橋・天王寺方面など市内のどのエリアからも通いやすいのが特長です。",
    body: [
      { h2: "大阪市はキッズダンスの選択肢が全国トップクラス", p: "ダンス文化が根付く大阪市は、子ども向けダンス教室の数・ジャンルとも全国屈指です。選択肢が多いからこそ、自宅や学校から通いやすいか、3歳から通えるクラスがあるか、発表会で大きな舞台を経験できるかを基準に絞り込むのがおすすめです。常設スタジオを構えるスクールなら天候に左右されず安定して通えます。まずは無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "大阪市内で子どもが通いやすいダンス教室の選び方は？", a: "御堂筋線・谷町線・大阪環状線など最寄り路線の駅から徒歩圏にあるかをまず確認しましょう。大阪市内は教室数が多いため、無料体験を2〜3校受けて雰囲気を比べるのもおすすめです。" }],
    schools: areaDanceSchools("大阪市", "大阪府") },
  "osaka/minoh": { name: "箕面市", prefName: "大阪府", prefSlug: "osaka",
    intro: "箕面市は2024年の北大阪急行延伸（箕面萱野・箕面船場阪大前駅の開業）でアクセスが向上した、大阪屈指の文教・子育てエリアです。3歳から通える子ども向けダンス教室を比較しました。",
    access: "北大阪急行の箕面萱野・箕面船場阪大前駅と、阪急箕面線の箕面・牧落・桜井駅を中心にスクールが点在し、市内全域から通いやすい環境です。",
    body: [
      { h2: "箕面市は子どものダンス環境が充実したエリア", p: "教育熱心なご家庭が多い箕面市は、子ども向けダンス教室の層が厚いエリアです。常設スタジオを構えるスクールもあり、天候に左右されず安定して通えます。自宅から通いやすい校舎か、3歳から始められるか、発表会の機会があるかを基準に選ぶと長く続けやすくなります。まずは無料体験でスタジオの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "箕面市のダンス教室は駅から通いやすいですか？", a: "阪急箕面線の牧落・桜井駅や、北大阪急行の箕面船場阪大前駅の周辺にスクールが点在しています。駅から徒歩圏の教室が多く、送り迎えしやすいエリアです。" }],
    schools: [
    { ...LYDIA, desc: "箕面市内に6校展開する人気No.1ダンススクール。牧落校・船場阪大前校・桜井校・森町校・彩都西校など箕面市内に多数展開。現役プロダンサー講師200名以上在籍。3歳のリトルクラスから本格コースまで充実。ヒップホップ・ジャズ・K-POPなど多ジャンル対応。", tags: ["箕面市内6校展開", "初回体験無料", "3歳〜OK", "プロ講師200名+", "多ジャンル対応", "発表会充実"] },
    EXPG, AVEX, BDC,
  ]},
  "osaka/moriguchi": { name: "守口市", prefName: "大阪府", prefSlug: "osaka",
    intro: "守口市は京阪本線とOsaka Metro谷町線が走る、大阪市に隣接した子育てしやすい住宅エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "京阪本線の守口市駅とOsaka Metro谷町線の守口・太子橋今市駅を中心にスクールが集まり、門真市・大阪市旭区方面からも通いやすい立地です。",
    body: [
      { h2: "守口市で子どもにダンスを習わせるなら", p: "大阪市中心部へのアクセスが良い守口市は、共働きのご家庭も多く、平日夕方や土曜のクラスが充実したスクールが人気です。常設スタジオを構えるスクールもあり、振替や進級もスムーズです。駅から徒歩圏で送り迎えしやすいか、3歳から通えるかを基準に選び、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "守口市のダンス教室は何歳から通えますか？", a: "守口市駅周辺のスクールでは3歳から通えるリトルクラスを用意しているところがあり、未就学のお子さんでも無理なく始められます。" }],
    schools: areaDanceSchools("守口市", "大阪府") },
  "osaka/sakai": { name: "堺市", prefName: "大阪府", prefSlug: "osaka",
    intro: "堺市は7つの区を持つ政令指定都市で、南海高野線・南海本線・JR阪和線が走る大阪南部の中心都市です。子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "南海高野線の堺東駅、南海本線の堺駅、Osaka Metro御堂筋線のなかもず駅周辺にスクールが集まり、市内各区から通いやすい立地です。",
    body: [
      { h2: "堺市でダンス教室を選ぶポイント", p: "堺市は区によって生活圏が分かれるため、自宅から無理なく送り迎えできる場所にあるかが教室選びの最重要ポイントです。堺東・なかもず周辺は乗り入れ路線が多く、習い事の選択肢も豊富です。3歳から通えるか、発表会の機会があるか、振替制度があるかを比較し、無料体験で雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "堺市で子どもが通えるダンス教室はどのエリアに多いですか？", a: "堺東駅・なかもず駅・堺駅といったターミナル周辺に集まっています。御堂筋線・南海線沿いなら大阪市方面からの帰りにも通いやすいです。" }],
    schools: areaDanceSchools("堺市", "大阪府") },
  "osaka/suita": { name: "吹田市", prefName: "大阪府", prefSlug: "osaka",
    intro: "吹田市は江坂や千里ニュータウンを擁する、大阪北部の子育て人気エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "Osaka Metro御堂筋線の江坂駅、阪急千里線の各駅、JR京都線の吹田駅周辺にスクールが点在し、豊中市・大阪市方面からも通いやすい立地です。",
    body: [
      { h2: "吹田市は子育て世帯にダンスが人気のエリア", p: "千里ニュータウンを中心に子育て世帯が多い吹田市では、幼児から小学生まで通えるダンス教室の需要が高まっています。江坂駅周辺は習い事の教室が集まるエリアで、選択肢が豊富です。3歳から通えるリトルクラスがあるか、駅から徒歩圏か、発表会があるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "吹田市のダンス教室は江坂エリアに多いですか？", a: "御堂筋線の江坂駅周辺は習い事教室が集まるエリアで、ダンス教室の選択肢も豊富です。阪急千里線・JR吹田駅周辺にも教室が点在しています。" }],
    schools: areaDanceSchools("吹田市", "大阪府") },
  "osaka/takatsuki": { name: "高槻市", prefName: "大阪府", prefSlug: "osaka",
    intro: "高槻市は大阪と京都のほぼ中間に位置し、JR京都線と阪急京都線の2路線が使える子育て人気エリアです。子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR高槻駅と阪急高槻市駅の周辺にスクールが集まり、茨木市・島本町など近隣エリアからも通いやすい立地です。",
    body: [
      { h2: "高槻市でダンス教室を選ぶポイント", p: "JRと阪急の2駅周辺に商業施設と教室が集まる高槻市は、習い事の送り迎えがしやすい街です。大阪・京都どちらに通勤するご家庭でも、駅前のスクールなら帰りに合わせて送迎しやすいのが利点です。3歳から通えるか、振替制度があるか、発表会の費用はどのくらいかを比較し、無料体験で確かめましょう。" },
    ],
    faqs: [{ q: "高槻市のダンス教室は駅から通いやすいですか？", a: "JR高槻駅・阪急高槻市駅の周辺に教室が集まっており、徒歩圏で通えるスクールが多いエリアです。駅前は人通りも多く、夕方のレッスン帰りも安心です。" }],
    schools: areaDanceSchools("高槻市", "大阪府") },
  "osaka/toyonaka": { name: "豊中市", prefName: "大阪府", prefSlug: "osaka",
    intro: "豊中市は阪急宝塚線と北大阪急行が走る、文教地区として知られる大阪北部の住宅都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "阪急宝塚線の豊中・岡町・曽根駅と、北大阪急行の千里中央・緑地公園駅周辺にスクールが点在し、市内全域から通いやすい環境です。",
    body: [
      { h2: "文教都市・豊中で子どもにダンスを", p: "教育環境の良さで知られる豊中市は、学習塾と習い事を両立するご家庭が多いエリアです。ダンスはリズム感・体力・表現力を育てながら、週1回から無理なく始められるのが魅力です。平日夕方や土曜のクラスがあるか、駅から徒歩圏かを基準に選ぶと続けやすくなります。まずは無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "豊中市で平日夕方に通えるダンス教室はありますか？", a: "豊中駅・千里中央駅周辺を中心に、放課後の時間帯にキッズクラスを設けているスクールがあります。学校帰りに通える駅近の教室を選ぶと送り迎えがスムーズです。" }],
    schools: areaDanceSchools("豊中市", "大阪府") },
  "osaka/ibaraki": { name: "茨木市", prefName: "大阪府", prefSlug: "osaka",
    intro: "茨木市はJR京都線・阪急京都線・大阪モノレールの3路線が使える、大阪北部の子育て人気エリアです。子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR茨木駅と阪急茨木市駅の周辺にスクールが集まり、摂津市・高槻市方面からも通いやすい立地です。",
    body: [
      { h2: "茨木市でダンス教室を選ぶポイント", p: "大学キャンパスが集まる茨木市は若い世帯の流入が続き、子ども向け習い事の需要が高いエリアです。JRと阪急の駅周辺に教室が集まっているため、自宅からの通いやすさで絞り込むのが効率的です。3歳から通えるか、発表会の機会があるか、月謝と諸費用のバランスを比較し、無料体験で雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "茨木市のダンス教室は何歳から通えますか？", a: "JR茨木駅・阪急茨木市駅周辺のスクールには3歳から通えるリトルクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("茨木市", "大阪府") },
  // ── 愛知県 ──
  "aichi/anjo": { name: "安城市", prefName: "愛知県", prefSlug: "aichi",
    intro: "安城市はJR東海道本線と名鉄西尾線が走る、西三河の子育てしやすい住宅都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR安城駅・三河安城駅と、名鉄西尾線の南安城・桜井駅周辺にスクールが点在し、刈谷市・知立市方面からも通いやすい立地です。",
    body: [
      { h2: "安城市で子どもにダンスを習わせるなら", p: "車での送り迎えを前提に教室を選べるのが安城市の特長です。常設スタジオを構えるスクールもあり、天候に左右されず安定して通えます。3歳から通えるリトルクラスがあるか、送迎のしやすさ、発表会の機会を基準に選ぶと長く続けやすくなります。まずは無料体験でスタジオの雰囲気と先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "安城市の桜井エリアにダンス教室はありますか？", a: "名鉄西尾線の桜井駅周辺にも子ども向けダンス教室があり、常設スタジオを構えるスクールも選べます。車での送迎がしやすいのが安城エリアの特長です。" }],
    schools: areaDanceSchools("安城市", "愛知県") },
  "aichi/chikusa": { name: "千種区", prefName: "愛知県", prefSlug: "aichi",
    intro: "名古屋市千種区は今池・星ヶ丘・覚王山を中心に、教育熱心なご家庭が集まるエリアです。子ども向けダンス教室を月謝・対象年齢・無料体験で比較しました。",
    access: "地下鉄東山線（今池・星ヶ丘・覚王山）と桜通線沿いにスクールが点在し、通学・通塾のついでにも通いやすいのが千種区の特長です。",
    body: [
      { h2: "千種区はダンスと勉強を両立しやすいエリア", p: "千種区は学習塾や習い事の選択肢が豊富で、ダンスでリズム感・体力・表現力を育てつつ、学業とも両立しやすい環境です。平日夕方や土曜のクラスが充実しているスクールを選べば、無理なく週のスケジュールに組み込めます。無料体験でクラスの時間帯と振替制度を確認しておくと安心です。" },
    ],
    faqs: [{ q: "千種区で平日夕方に通えるダンス教室はありますか？", a: "今池・星ヶ丘エリアを中心に、放課後の時間帯にキッズクラスを設けているスクールがあります。学年やレベルでクラスが分かれているスクールを選ぶと続けやすいです。" }],
    schools: areaDanceSchools("千種区", "愛知県") },
  "aichi/meito": { name: "名東区", prefName: "愛知県", prefSlug: "aichi",
    intro: "名古屋市名東区は藤が丘・上社を中心に新しい住宅街が広がる、子育てファミリーの多いエリアです。3歳から通える子ども向けダンス教室を比較しました。",
    access: "地下鉄東山線の藤が丘・上社・一社の各駅周辺にスクールが集まり、名東区内や長久手市方面からも通いやすい立地です。",
    body: [
      { h2: "名東区で初めてダンスを習うなら", p: "名東区は3歳〜小学生の子育て世帯が多く、初心者向けのリトルクラスを設けるスクールが増えています。最初は週1回から始め、慣れてきたらジャンルやクラスを増やせる柔軟なスクールを選ぶと、子どものペースで続けられます。" },
    ],
    faqs: [{ q: "名東区のダンス教室は何歳から通えますか？", a: "藤が丘・上社エリアのスクールでは3歳から通えるリトルクラスを用意しているところが多く、未就学児でも無理なく始められます。" }],
    schools: areaDanceSchools("名東区", "愛知県") },
  "aichi/midori": { name: "緑区", prefName: "愛知県", prefSlug: "aichi",
    intro: "名古屋市緑区は徳重・鳴海エリアを中心に人口が増え続ける、名古屋市内有数の子育てエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "地下鉄桜通線の徳重駅と名鉄名古屋本線の鳴海・有松駅周辺にスクールが点在し、商業施設と合わせて送り迎えしやすい環境です。",
    body: [
      { h2: "緑区は子どもの数が多いダンス需要の高いエリア", p: "緑区は名古屋市内でも子育て世帯が多く、幼児・小学生向けの習い事が充実しています。徳重駅周辺は商業施設が集まり、買い物と送迎を兼ねられるのが便利です。3歳から通えるか、週1回から始められるか、発表会で舞台経験を積めるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "緑区の徳重エリアに子ども向けダンス教室はありますか？", a: "桜通線終点の徳重駅周辺は子育て世帯が多く、キッズ向けダンスクラスを設ける教室が点在しています。商業施設と合わせて送迎しやすいエリアです。" }],
    schools: areaDanceSchools("緑区", "愛知県") },
  "aichi/moriyama": { name: "守山区", prefName: "愛知県", prefSlug: "aichi",
    intro: "名古屋市守山区は名鉄瀬戸線とJR中央本線が走る、緑豊かな住宅エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "名鉄瀬戸線の小幡・喜多山駅とJR中央本線の新守山駅周辺にスクールが点在し、尾張旭市・千種区方面からも通いやすい立地です。",
    body: [
      { h2: "守山区で子どもにダンスを習わせるなら", p: "落ち着いた住宅街が広がる守山区は、無理のない月謝で習い事を始めやすいエリアです。ダンスは週1回から始められ、体力づくりとリズム感を同時に育てられます。駅から徒歩圏か、車での送迎がしやすいか、振替制度があるかを確認し、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "守山区のダンス教室は何歳から通えますか？", a: "小幡・新守山駅周辺のスクールでは3歳から通えるクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("守山区", "愛知県") },
  "aichi/nisshin": { name: "日進市", prefName: "愛知県", prefSlug: "aichi",
    intro: "日進市は名古屋市と豊田市の間に位置し、子育て世帯の流入が続く愛知県有数の人口増加エリアです。3歳から通える子ども向けダンス教室を比較しました。",
    access: "地下鉄鶴舞線直通・名鉄豊田線の日進・米野木・赤池駅周辺にスクールが点在し、名古屋市天白区・みよし市方面からも通いやすい立地です。",
    body: [
      { h2: "日進市は子育て世帯に選ばれるダンス環境", p: "新しい住宅街が広がる日進市は子どもの数が多く、幼児から通える習い事の需要が高いエリアです。常設スタジオを構えるスクールもあり、天候に左右されず安定して通えます。3歳から通えるリトルクラスがあるか、車での送迎のしやすさ、発表会の機会を基準に選び、無料体験でスタジオの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "日進市に常設のダンススタジオはありますか？", a: "日進市内には常設スタジオを構える子ども向けダンススクールがあり、毎週同じ場所で安定してレッスンを受けられます。車での送迎がしやすいのも特長です。" }],
    schools: areaDanceSchools("日進市", "愛知県") },
  "aichi/owariasahi": { name: "尾張旭市", prefName: "愛知県", prefSlug: "aichi",
    intro: "尾張旭市は名鉄瀬戸線で名古屋中心部とつながる、コンパクトで子育てしやすい住宅都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "名鉄瀬戸線の尾張旭・三郷・旭前駅周辺にスクールが点在し、瀬戸市・守山区方面からも通いやすい立地です。",
    body: [
      { h2: "尾張旭市で子どもにダンスを習わせるなら", p: "市域がコンパクトな尾張旭市は、自転車や車で送り迎えしやすいのが習い事選びの強みです。隣接する守山区・瀬戸市まで含めると教室の選択肢が広がります。3歳から通えるか、週1回から無理なく始められるか、発表会で舞台に立つ機会があるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "尾張旭市のダンス教室は車で送迎しやすいですか？", a: "尾張旭市は市域がコンパクトで車での送迎を前提に通いやすいエリアです。名鉄瀬戸線沿いなら電車での通学も可能です。" }],
    schools: areaDanceSchools("尾張旭市", "愛知県") },
  "aichi/tenpaku": { name: "天白区", prefName: "愛知県", prefSlug: "aichi",
    intro: "名古屋市天白区は地下鉄鶴舞線沿いに住宅街が広がる、子育て世帯の多いエリアです。塩釜口・植田・原・平針を中心に、3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "地下鉄鶴舞線の塩釜口・植田・原・平針の各駅周辺にスクールが集まり、天白区内はもちろん日進市・名東区方面からも通いやすい立地です。",
    body: [
      { h2: "天白区で子どもにダンスを習わせる前に確認したいこと", p: "天白区は名城大学天白キャンパスを抱える文教エリアで、習い事に熱心なご家庭が多い地域です。週1回・3歳から始められるか、ヒップホップやK-POPなどジャンルを選べるか、発表会で舞台に立つ機会があるかを基準に選ぶと、長く続けやすくなります。まずは無料体験で先生との相性とスタジオの雰囲気を確かめるのがおすすめです。" },
    ],
    faqs: [{ q: "天白区のダンス教室は塩釜口・植田あたりにありますか？", a: "地下鉄鶴舞線の塩釜口・植田・原エリアを中心に子ども向けダンス教室が点在しています。駅から徒歩圏で通えるスクールも多く、送り迎えがしやすいのが特長です。" }],
    schools: areaDanceSchools("天白区", "愛知県") },
  "aichi/toyota": { name: "豊田市", prefName: "愛知県", prefSlug: "aichi",
    intro: "豊田市は愛知県内最大の面積を持つ、子育て支援が手厚いものづくりの街です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "名鉄豊田市駅・愛知環状鉄道新豊田駅周辺の市街地にスクールが集まり、市内各地から車でも通いやすい立地です。",
    body: [
      { h2: "豊田市でダンス教室を選ぶポイント", p: "車社会の豊田市では、駐車のしやすさと自宅からの距離が教室選びの大きなポイントです。豊田市駅周辺は商業施設が集まり、買い物と送迎を兼ねられます。3歳から通えるリトルクラスがあるか、発表会の機会があるか、月謝と諸費用のバランスを比較し、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "豊田市のダンス教室は何歳から通えますか？", a: "豊田市駅周辺のスクールでは3歳から通えるクラスを設けているところがあり、幼稚園・保育園と並行して無理なく始められます。" }],
    schools: areaDanceSchools("豊田市", "愛知県") },
  // ── 千葉県 ──
  "chiba/chiba-city": { name: "千葉市", prefName: "千葉県", prefSlug: "chiba",
    intro: "千葉市は6つの区からなる政令指定都市で、JR・京成・千葉都市モノレールが市内を結ぶ県都です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR千葉駅・京成千葉駅と千葉都市モノレール沿線、美浜区の海浜幕張駅周辺にスクールが点在し、市内各区から通いやすい立地です。",
    body: [
      { h2: "千葉市でダンス教室を選ぶポイント", p: "千葉市は区ごとに生活圏が分かれるため、自宅から無理なく送り迎えできるかが教室選びの最重要ポイントです。千葉駅周辺は路線が集まり選択肢が豊富で、海浜幕張エリアは商業施設と合わせて通いやすいのが特長です。3歳から通えるか、振替制度があるかを確認し、無料体験で雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "千葉市で子どもが通えるダンス教室はどのエリアに多いですか？", a: "JR千葉駅・京成千葉駅周辺と海浜幕張エリアに教室が集まっています。モノレール沿線なら稲毛・都賀方面からも通いやすいです。" }],
    schools: areaDanceSchools("千葉市", "千葉県") },
  "chiba/kashiwa": { name: "柏市", prefName: "千葉県", prefSlug: "chiba",
    intro: "柏市はJR常磐線・東武アーバンパークライン・つくばエクスプレスが走る、千葉県北西部の中心都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "柏駅周辺の商業エリアにスクールが集まるほか、つくばエクスプレスの柏の葉キャンパス駅周辺にも教室が点在し、流山市・我孫子市方面からも通いやすい立地です。",
    body: [
      { h2: "柏市はキッズダンスの盛んなエリア", p: "ストリートダンス文化が根付く柏市は、子ども向けダンス教室の層が厚いエリアです。柏駅周辺は習い事の選択肢が豊富で、教室同士を比較しやすいのが利点です。3歳から通えるか、発表会やイベント出演の機会があるか、月謝と諸費用を比較し、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "柏駅周辺に子ども向けのダンス教室はありますか？", a: "柏駅から徒歩圏に子ども向けのダンス教室が複数あります。電車でも通いやすく、送り迎えしやすいのが柏エリアの特長です。" }],
    schools: areaDanceSchools("柏市", "千葉県") },
  "chiba/matsudo": { name: "松戸市", prefName: "千葉県", prefSlug: "chiba",
    intro: "松戸市はJR常磐線・武蔵野線で都心と直結する、東京に隣接した子育て支援に力を入れる街です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR松戸駅・新松戸駅を中心にスクールが点在し、市川市・流山市方面からも通いやすい立地です。",
    body: [
      { h2: "松戸市で子どもにダンスを習わせるなら", p: "子育て支援の手厚さで知られる松戸市は、共働きのご家庭が多く、平日夕方や土日のクラスが充実したスクールが人気です。松戸駅周辺は商業施設も多く、送り迎えのついでに買い物を済ませられます。3歳から通えるか、振替制度があるかを確認し、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "松戸市のダンス教室は何歳から通えますか？", a: "松戸駅・新松戸駅周辺のスクールには3歳から通えるリトルクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("松戸市", "千葉県") },
  // ── 岐阜県 ──
  "gifu/gifu-city": { name: "岐阜市", prefName: "岐阜県", prefSlug: "gifu",
    intro: "岐阜市はJR岐阜駅・名鉄岐阜駅を中心に市街地が広がる岐阜県の県都です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR岐阜駅・名鉄岐阜駅周辺にスクールが集まり、各務原市・岐南町など近隣からも通いやすい立地です。",
    body: [
      { h2: "岐阜市で子どもにダンスを習わせるなら", p: "岐阜市は常設スタジオを構えるダンススクールもあり、天候に左右されず毎週同じ場所で安定してレッスンを受けられます。車での送迎がしやすいか、3歳から通えるリトルクラスがあるか、発表会で舞台経験を積めるかを基準に選ぶと長く続けやすくなります。まずは無料体験で先生との相性とスタジオの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "岐阜市に常設のダンススタジオはありますか？", a: "岐阜市内には常設スタジオを構える子ども向けダンススクールがあります。レンタルスタジオ型と違い、毎週同じ場所で安定して通えるのが利点です。" }],
    schools: areaDanceSchools("岐阜市", "岐阜県") },
  "gifu/kani": { name: "可児市", prefName: "岐阜県", prefSlug: "gifu",
    intro: "可児市は名鉄広見線とJR太多線が走る、名古屋方面へ通勤するご家庭も多い住宅都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "名鉄広見線の新可児駅・JR太多線の可児駅周辺を中心にスクールが点在し、車での送迎を前提に通いやすいエリアです。",
    body: [
      { h2: "可児市で子どもにダンスを習わせるなら", p: "車移動が中心の可児市では、駐車のしやすさと自宅からの距離が教室選びのポイントです。隣接する美濃加茂市・多治見市まで含めると選択肢が広がります。3歳から通えるか、週1回から無理なく始められるか、発表会の機会があるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "可児市のダンス教室は車で送迎しやすいですか？", a: "可児市は車での送迎を前提に通いやすいエリアです。新可児駅・可児駅周辺なら電車での通学もでき、近隣市の教室も選択肢に入ります。" }],
    schools: areaDanceSchools("可児市", "岐阜県") },
  "gifu/minokamo": { name: "美濃加茂市", prefName: "岐阜県", prefSlug: "gifu",
    intro: "美濃加茂市はJR高山本線・太多線と長良川鉄道が交わる、岐阜県中南部の生活拠点です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR美濃太田駅を中心にスクールが点在し、可児市・関市・坂祝町など近隣からも車で通いやすい立地です。",
    body: [
      { h2: "美濃加茂市で子どもにダンスを習わせるなら", p: "美濃加茂市は岐阜県中南部の買い物・生活の拠点で、近隣の市町からも習い事に通いやすいエリアです。車での送迎が中心になるため、駐車のしやすさとレッスン時間帯が教室選びのポイントです。3歳から通えるか、発表会の機会があるかを確認し、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "美濃加茂市のダンス教室は何歳から通えますか？", a: "美濃太田駅周辺のスクールには3歳から通えるクラスを設けているところがあり、幼稚園・保育園と並行して無理なく始められます。" }],
    schools: areaDanceSchools("美濃加茂市", "岐阜県") },
  "gifu/tajimi": { name: "多治見市", prefName: "岐阜県", prefSlug: "gifu",
    intro: "多治見市はJR中央本線で名古屋方面と直結する、岐阜県東濃エリアの中心都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR多治見駅を中心にスクールが点在し、土岐市・可児市など東濃エリア各地から車でも電車でも通いやすい立地です。",
    body: [
      { h2: "多治見市で子どもにダンスを習わせるなら", p: "東濃エリアの習い事の拠点となる多治見市は、多治見駅周辺なら電車通学も可能で、車での送迎にも対応しやすいのが特長です。3歳から通えるリトルクラスがあるか、週1回から始められるか、発表会で舞台に立てるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "多治見市のダンス教室は電車でも通えますか？", a: "JR多治見駅周辺の教室なら電車での通学が可能です。土岐市・可児市方面からも通いやすく、車での送迎と使い分けられます。" }],
    schools: areaDanceSchools("多治見市", "岐阜県") },
  // ── 兵庫県 ──
  "hyogo/nishinomiya": { name: "西宮市", prefName: "兵庫県", prefSlug: "hyogo",
    intro: "西宮市は阪急・JR・阪神の3路線が市内を走る、関西屈指の文教・子育てエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "阪急西宮北口駅・JR西宮駅・阪神西宮駅の周辺にスクールが集まり、尼崎市・芦屋市方面からも通いやすい立地です。",
    body: [
      { h2: "文教都市・西宮はダンスと勉強を両立しやすい", p: "住みたい街として人気の西宮市は、学習塾も習い事も選択肢が豊富なエリアです。特に西宮北口駅周辺は教室が集まり、比較検討しやすいのが利点です。学業と両立するなら、平日夕方や土曜のクラスがあるか、振替制度があるかを確認しましょう。まずは無料体験で先生との相性を確かめるのがおすすめです。" },
    ],
    faqs: [{ q: "西宮北口の周辺に子ども向けダンス教室はありますか？", a: "西宮北口駅は習い事教室が集まる阪神間有数のエリアで、子ども向けダンスクラスを設ける教室も複数あります。駅から徒歩圏で送り迎えしやすいのが特長です。" }],
    schools: areaDanceSchools("西宮市", "兵庫県") },
  // ── 茨城県 ──
  "ibaraki/hitachi": { name: "日立市", prefName: "茨城県", prefSlug: "ibaraki",
    intro: "日立市は太平洋に面した茨城県北部の中核都市で、JR常磐線が市内を縦断します。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR常磐線の日立駅・常陸多賀駅周辺にスクールが点在し、車での送迎を前提に市内各地から通いやすいエリアです。",
    body: [
      { h2: "日立市で子どもにダンスを習わせるなら", p: "車移動が中心の日立市では、自宅からの距離と駐車のしやすさが教室選びのポイントです。市域が南北に長いため、学校や自宅に近いエリアの教室から検討するのが効率的です。3歳から通えるか、週1回から無理なく始められるか、発表会の機会があるかを確認し、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "日立市のダンス教室は何歳から通えますか？", a: "日立駅・常陸多賀駅周辺のスクールには3歳から通えるクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("日立市", "茨城県") },
  "ibaraki/hitachinaka": { name: "ひたちなか市", prefName: "茨城県", prefSlug: "ibaraki",
    intro: "ひたちなか市はJR常磐線の勝田駅を中心に発展した、水戸市に隣接する住宅都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR常磐線の勝田駅周辺にスクールが点在し、水戸市・那珂市方面からも車で通いやすい立地です。",
    body: [
      { h2: "ひたちなか市で子どもにダンスを習わせるなら", p: "大型商業施設が集まるひたちなか市は、買い物と習い事の送迎を兼ねやすいエリアです。隣接する水戸市まで含めると教室の選択肢が広がります。3歳から通えるリトルクラスがあるか、車での送迎のしやすさ、発表会で舞台に立つ機会があるかを基準に選び、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "ひたちなか市のダンス教室は車で送迎しやすいですか？", a: "ひたちなか市は車での送迎を前提に通いやすいエリアです。勝田駅周辺なら電車も使え、水戸市の教室も選択肢に入ります。" }],
    schools: areaDanceSchools("ひたちなか市", "茨城県") },
  "ibaraki/mito": { name: "水戸市", prefName: "茨城県", prefSlug: "ibaraki",
    intro: "水戸市は茨城県の県都として商業・教育機能が集まる、県内最大の習い事エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR水戸駅を中心に市内各地へバス路線が伸び、スクールは駅周辺と郊外のロードサイドに点在しています。車での送迎にも対応しやすいエリアです。",
    body: [
      { h2: "水戸市でダンス教室を選ぶポイント", p: "県都・水戸市は子ども向けダンス教室の選択肢が県内で最も豊富なエリアです。選択肢が多いからこそ、自宅からの通いやすさ、3歳から通えるクラスの有無、発表会やイベント出演の機会を基準に絞り込むのがおすすめです。気になる教室は無料体験を2〜3校受けて、先生との相性で決めると失敗しにくくなります。" },
    ],
    faqs: [{ q: "水戸市で子どもが通えるダンス教室は多いですか？", a: "県都の水戸市は教室数が多く、ヒップホップ・K-POP・ジャズなどジャンルの選択肢も豊富です。無料体験で複数校を比較するのがおすすめです。" }],
    schools: areaDanceSchools("水戸市", "茨城県") },
  "ibaraki/tsuchiura": { name: "土浦市", prefName: "茨城県", prefSlug: "ibaraki",
    intro: "土浦市は霞ヶ浦のほとりに広がる茨城県南部の中核都市で、JR常磐線で都心方面ともつながります。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR常磐線の土浦駅周辺にスクールが点在し、かすみがうら市・阿見町など近隣からも車で通いやすい立地です。",
    body: [
      { h2: "土浦市で子どもにダンスを習わせるなら", p: "車移動が中心の土浦市では、駐車のしやすさと自宅からの距離が教室選びのポイントです。隣接するつくば市まで含めると教室の選択肢が広がります。3歳から通えるか、週1回から無理なく始められるか、発表会の機会があるかを確認し、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "土浦市のダンス教室は何歳から通えますか？", a: "土浦駅周辺のスクールには3歳から通えるクラスを設けているところがあり、幼稚園・保育園と並行して無理なく始められます。" }],
    schools: areaDanceSchools("土浦市", "茨城県") },
  "ibaraki/tsukuba": { name: "つくば市", prefName: "茨城県", prefSlug: "ibaraki",
    intro: "つくば市は研究学園都市として発展し、教育熱心な子育て世帯が集まる茨城県南部の人気エリアです。3歳から通える子ども向けダンス教室を比較しました。",
    access: "つくばエクスプレスのつくば駅・研究学園駅周辺にスクールが集まり、市内各地から車でも通いやすい立地です。",
    body: [
      { h2: "つくば市は教育熱心な家庭が多いダンス人気エリア", p: "研究機関や大学が集まるつくば市は、子どもの習い事への関心が高いエリアです。つくば駅・研究学園駅周辺は新しい商業施設が多く、買い物と送迎を兼ねられます。学業と両立しやすい平日夕方・土日のクラスがあるか、3歳から通えるかを基準に選び、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "つくば市のダンス教室は研究学園エリアにありますか？", a: "つくばエクスプレスの研究学園駅・つくば駅周辺に子ども向けダンス教室が点在しています。車での送迎がしやすく、駐車場のある施設も多いエリアです。" }],
    schools: areaDanceSchools("つくば市", "茨城県") },
  // ── 石川県 ──
  "ishikawa/kanazawa": { name: "金沢市", prefName: "石川県", prefSlug: "ishikawa",
    intro: "金沢市は北陸新幹線で首都圏ともつながる北陸最大の都市で、子ども向け習い事の選択肢も豊富です。3歳から通えるダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "金沢駅を中心にバス網が市内全域をカバーし、スクールは中心部と郊外のロードサイドに点在しています。車での送迎にも対応しやすいエリアです。",
    body: [
      { h2: "金沢市で子どもにダンスを習わせるなら", p: "北陸最大の都市・金沢は、ヒップホップ・K-POP・ジャズなどジャンルの選択肢が豊富なエリアです。常設スタジオを構えるスクールもあり、雪の多い冬でも毎週同じ場所で安定して通えます。3歳から通えるリトルクラスがあるか、駐車のしやすさ、発表会の機会を基準に選び、無料体験でスタジオの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "金沢市に常設のダンススタジオはありますか？", a: "金沢市内には常設スタジオを構える子ども向けダンススクールがあります。冬場の天候に左右されず安定して通えるのが常設型の利点です。" }],
    schools: areaDanceSchools("金沢市", "石川県") },
  "ishikawa/nonoichi": { name: "野々市市", prefName: "石川県", prefSlug: "ishikawa",
    intro: "野々市市は金沢市に隣接し、住みよさの評価が高い子育て人気の街です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "野々市駅周辺と北陸鉄道石川線沿線にスクールが点在し、金沢市南部からも車で通いやすい立地です。",
    body: [
      { h2: "野々市市で子どもにダンスを習わせるなら", p: "コンパクトな市域に商業施設と住宅街がまとまる野々市市は、車での送り迎えがしやすい習い事向きの街です。隣接する金沢市の教室まで含めると選択肢が大きく広がります。3歳から通えるか、週1回から無理なく始められるか、発表会の機会があるかを確認し、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "野々市市から通えるダンス教室はありますか？", a: "野々市市内のほか、隣接する金沢市の教室にも車で通いやすい立地です。常設スタジオを構えるスクールも選択肢に入ります。" }],
    schools: areaDanceSchools("野々市市", "石川県") },
  "ishikawa/uchinada": { name: "内灘町", prefName: "石川県", prefSlug: "ishikawa",
    intro: "内灘町は金沢市の北西に隣接する、海沿いの子育てしやすい住宅の町です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "北陸鉄道浅野川線の内灘駅を起点に金沢市中心部へつながり、車なら金沢市内の教室にも通いやすい立地です。",
    body: [
      { h2: "内灘町で子どもにダンスを習わせるなら", p: "内灘町は金沢市中心部まで車で通いやすく、町内だけでなく金沢市の教室も含めて選べるのが特長です。送り迎えの負担を考え、自宅からの距離とレッスン時間帯を軸に絞り込みましょう。3歳から通えるか、発表会で舞台経験を積めるかも確認し、無料体験で先生との相性を確かめるのがおすすめです。" },
    ],
    faqs: [{ q: "内灘町から子どもが通えるダンス教室はありますか？", a: "内灘町内および隣接する金沢市内の教室が選択肢になります。浅野川線や車で金沢方面に出やすく、送迎しやすいエリアです。" }],
    schools: areaDanceSchools("内灘町", "石川県") },
  // ── 神奈川県 ──
  "kanagawa/aoba": { name: "青葉区", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "横浜市青葉区は青葉台・たまプラーザ・あざみ野が並ぶ、東急田園都市線沿線屈指の文教・子育てエリアです。3歳から通える子ども向けダンス教室を比較しました。",
    access: "東急田園都市線の青葉台・たまプラーザ・あざみ野駅周辺にスクールが集まり、こどもの国線沿線や緑区方面からも通いやすい立地です。",
    body: [
      { h2: "青葉区は習い事への意識が高いエリア", p: "教育熱心なご家庭が多い青葉区は、ダンス・ピアノ・学習塾など習い事の選択肢が豊富なエリアです。だからこそ、駅から徒歩圏で送り迎えしやすいか、3歳から通えるか、発表会で舞台経験を積めるかを基準に絞り込むのがおすすめです。まずは無料体験で先生との相性とクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "青葉区のダンス教室はどの駅周辺に多いですか？", a: "青葉台・たまプラーザ・あざみ野の各駅周辺に子ども向けダンス教室が集まっています。田園都市線沿線は駅徒歩圏の教室が多く、送り迎えしやすいエリアです。" }],
    schools: areaDanceSchools("青葉区", "神奈川県") },
  "kanagawa/atsugi": { name: "厚木市", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "厚木市は小田急線の本厚木駅を中心に商業が集まる、県央エリアの中心都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "小田急小田原線の本厚木駅周辺にスクールが集まり、愛川町・伊勢原市など県央各地からバス・車でも通いやすい立地です。",
    body: [
      { h2: "厚木市でダンス教室を選ぶポイント", p: "本厚木駅周辺は県央エリア最大の商業地で、子ども向けダンス教室の選択肢も豊富です。駅近の教室なら電車・バス通学がしやすく、郊外の教室なら車での送迎に向いています。3歳から通えるか、振替制度があるか、発表会の費用はどのくらいかを比較し、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "本厚木駅周辺に子ども向けダンス教室はありますか？", a: "本厚木駅周辺には子ども向けダンスクラスを設ける教室が複数あります。駅徒歩圏の教室なら、学校帰りや買い物のついでに通いやすいです。" }],
    schools: areaDanceSchools("厚木市", "神奈川県") },
  "kanagawa/ebina": { name: "海老名市", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "海老名市は小田急・相鉄・JRの3路線が乗り入れ、駅前開発で子育て世帯が増え続ける県央の人気エリアです。3歳から通える子ども向けダンス教室を比較しました。",
    access: "小田急線・相鉄線・JR相模線が交わる海老名駅を中心にスクールが集まり、座間市・綾瀬市方面からも通いやすい立地です。",
    body: [
      { h2: "海老名市は子育て世帯が増えるダンス人気エリア", p: "駅前再開発で人口が増え続ける海老名市は、子ども向け習い事の需要が高いエリアです。常設スタジオを構えるスクールもあり、天候に左右されず安定して通えます。駅から徒歩圏か、3歳から通えるか、発表会で舞台に立つ機会があるかを基準に選び、無料体験でスタジオの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "海老名駅周辺に常設のダンススタジオはありますか？", a: "海老名駅周辺には常設スタジオを構える子ども向けダンススクールがあります。3路線が使えるため、近隣市からも通いやすいのが特長です。" }],
    schools: areaDanceSchools("海老名市", "神奈川県") },
  "kanagawa/fujisawa": { name: "藤沢市", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "藤沢市は湘南エリアの中心都市で、JR東海道線・小田急江ノ島線・江ノ電が乗り入れます。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR・小田急が交わる藤沢駅と辻堂駅周辺にスクールが集まり、鎌倉市・茅ヶ崎市方面からも通いやすい立地です。",
    body: [
      { h2: "湘南・藤沢で子どもにダンスを", p: "ストリートカルチャーが身近な湘南エリアは、子どもがダンスを始めるのに良い環境です。藤沢駅・辻堂駅周辺は商業施設が多く、送迎と買い物を兼ねられます。3歳から通えるか、発表会の機会があるか、月謝と諸費用のバランスを確認し、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "藤沢市のダンス教室はどの駅周辺に多いですか？", a: "藤沢駅と辻堂駅の周辺に子ども向けダンス教室が集まっています。駅徒歩圏の教室が多く、電車でも車でも通いやすいエリアです。" }],
    schools: areaDanceSchools("藤沢市", "神奈川県") },
  "kanagawa/kohoku": { name: "港北区", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "横浜市港北区は綱島・日吉・大倉山が並ぶ東急東横線沿線の人気住宅エリアで、子育て世帯の多さは横浜市内でも有数です。3歳から通える子ども向けダンス教室を比較しました。",
    access: "東急東横線の綱島・日吉・大倉山駅周辺にスクールが集まり、新横浜・菊名方面からも通いやすい立地です。",
    body: [
      { h2: "港北区で子どもにダンスを習わせるなら", p: "人口の多い港北区は子ども向け習い事の激戦区で、ダンス教室の選択肢も豊富です。東横線沿線は駅徒歩圏の教室が多く、共働きのご家庭でも送り迎えしやすいのが特長です。3歳から通えるリトルクラスがあるか、平日夕方・土日のクラスがあるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "港北区のダンス教室は何歳から通えますか？", a: "綱島・日吉・大倉山駅周辺のスクールには3歳から通えるリトルクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("港北区", "神奈川県") },
  "kanagawa/midori": { name: "緑区", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "横浜市緑区は中山・長津田・十日市場が並ぶJR横浜線沿線の、緑豊かな子育てエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR横浜線の中山・十日市場・長津田駅周辺にスクールが点在し、中山駅は地下鉄グリーンラインも使えるため都筑区方面からも通いやすい立地です。",
    body: [
      { h2: "緑区で子どもにダンスを習わせるなら", p: "横浜線とグリーンラインが使える緑区は、隣接する青葉区・都筑区の教室まで含めて選べるのが特長です。駅から徒歩圏か、3歳から通えるか、週1回から無理なく始められるかを基準に絞り込みましょう。発表会で舞台に立つ経験は自信につながります。まずは無料体験で先生との相性を確かめるのがおすすめです。" },
    ],
    faqs: [{ q: "緑区のダンス教室はどの駅周辺にありますか？", a: "中山・十日市場・長津田の各駅周辺に子ども向けダンス教室が点在しています。長津田駅は田園都市線も使え、通学の選択肢が広いエリアです。" }],
    schools: areaDanceSchools("緑区", "神奈川県") },
  "kanagawa/nakahara": { name: "中原区", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "川崎市中原区は武蔵小杉のタワーマンション群を中心に、子育て世帯が急増しているエリアです。武蔵小杉・元住吉・武蔵中原周辺の子ども向けダンス教室を比較しました。",
    access: "JR南武線・横須賀線・東急東横線が乗り入れる武蔵小杉駅を中心にスクールが集まり、元住吉・武蔵中原・武蔵新城方面からも通いやすい立地です。",
    body: [
      { h2: "武蔵小杉でダンス教室を選ぶポイント", p: "武蔵小杉は共働きのご家庭が多く、平日夕方や土日のクラスが充実したスクールが人気です。駅近で送迎しやすいか、3歳から通えるか、発表会で舞台を経験できるかを基準に選ぶと、子どもが長く続けやすくなります。常設スタジオを構えるスクールなら、振替や進級もスムーズです。" },
    ],
    faqs: [{ q: "武蔵小杉エリアに常設のダンススタジオはありますか？", a: "武蔵小杉駅周辺には常設スタジオを構える子ども向けダンススクールがあり、天候に左右されず安定して通えます。駅直結・駅近で送り迎えしやすい点も共働き家庭に好評です。" }],
    schools: areaDanceSchools("中原区", "神奈川県") },
  "kanagawa/nakahara-shinjou": { name: "中原区（新城）", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "川崎市中原区・武蔵新城エリアは南武線沿いの住宅街で、子育て世帯に人気の地域です。武蔵新城・武蔵中原・武蔵小杉周辺の子ども向けダンス教室を比較しました。",
    access: "JR南武線の武蔵新城・武蔵中原駅周辺にスクールが点在し、隣接する武蔵小杉エリアまで足を伸ばせば選択肢がさらに広がります。",
    body: [
      { h2: "武蔵新城・武蔵小杉エリアのダンス教室事情", p: "武蔵小杉の再開発でファミリー層が急増した中原区は、子ども向けダンス教室の需要が高いエリアです。武蔵新城からは1駅の武蔵小杉に常設スタジオを構えるスクールもあり、通いやすさとレッスンの質を両立できます。まずは無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "武蔵新城から通いやすいダンス教室はありますか？", a: "武蔵新城駅周辺のほか、南武線で1駅の武蔵小杉エリアにも子ども向けスクールが集まっています。徒歩圏か、駅から送迎しやすいかを基準に選ぶと続けやすいです。" }],
    schools: areaDanceSchools("新城", "神奈川県") },
  "kanagawa/sagamihara": { name: "相模原市", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "相模原市は3つの区からなる政令指定都市で、小田急線・JR横浜線が市内を走ります。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR横浜線の橋本・相模原駅、小田急線の相模大野・東林間駅周辺にスクールが点在し、町田市方面からも通いやすい立地です。",
    body: [
      { h2: "相模原市でダンス教室を選ぶポイント", p: "市域の広い相模原市では、自宅最寄りの沿線で教室を絞り込むのが効率的です。相模大野・橋本といったターミナル周辺は選択肢が豊富で、東林間など住宅街の駅にも教室が点在しています。3歳から通えるか、振替制度があるか、発表会の機会があるかを比較し、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "相模原市のダンス教室はどのエリアに多いですか？", a: "相模大野・橋本・相模原の各駅周辺に教室が集まっています。小田急江ノ島線の東林間駅など住宅街の駅周辺にも子ども向けの教室があります。" }],
    schools: areaDanceSchools("相模原市", "神奈川県") },
  "kanagawa/takatsu": { name: "高津区", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "川崎市高津区は溝の口（武蔵溝ノ口）を中心に、田園都市線・南武線が交わる交通至便なエリアです。子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "東急田園都市線・JR南武線の溝の口／武蔵溝ノ口駅を中心にスクールが集まり、高津区内はもちろん宮前区・中原区方面からもアクセスしやすい立地です。",
    body: [
      { h2: "高津区はダンス教室の選択肢が多いエリア", p: "溝の口は商業施設と住宅街が共存する川崎屈指のターミナルで、子ども向けダンス教室の選択肢も豊富です。駅近で送り迎えがしやすいか、振替制度があるか、発表会の費用はどのくらいかを比較して選ぶと失敗しにくくなります。気になるスクールは無料体験で雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "溝の口周辺で子どもが通えるダンス教室はありますか？", a: "溝の口・武蔵溝ノ口駅周辺には子ども向けのダンス教室が複数あります。駅から徒歩圏で通えるスクールも多く、習い事の送り迎えがしやすいエリアです。" }],
    schools: areaDanceSchools("高津区", "神奈川県") },
  "kanagawa/tsuzuki": { name: "都筑区", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "横浜市都筑区は港北ニュータウンを中心に計画的に整備された、横浜市内屈指の子育てエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "地下鉄ブルーライン・グリーンラインが交わるセンター北・センター南駅周辺にスクールが集まり、港北区・緑区方面からも通いやすい立地です。",
    body: [
      { h2: "都筑区は子育て世帯が多いダンス人気エリア", p: "港北ニュータウンを擁する都筑区は子どもの数が多く、習い事の環境が整ったエリアです。センター北・センター南周辺は大型商業施設が集まり、買い物と送迎を兼ねられるのが便利です。3歳から通えるリトルクラスがあるか、発表会で舞台経験を積めるかを基準に選び、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "センター北・センター南に子ども向けダンス教室はありますか？", a: "センター北・センター南駅周辺は子ども向け習い事教室が集まるエリアで、ダンスクラスを設ける教室も複数あります。駅徒歩圏で送り迎えしやすいのが特長です。" }],
    schools: areaDanceSchools("都筑区", "神奈川県") },
  "kanagawa/yamato": { name: "大和市", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "大和市は小田急江ノ島線・相鉄本線・東急田園都市線（中央林間）が使える、交通利便性の高い住宅都市です。3歳から通える子ども向けダンス教室を比較しました。",
    access: "小田急・相鉄が交わる大和駅と、田園都市線の始発駅・中央林間駅の周辺にスクールが点在し、座間市・綾瀬市方面からも通いやすい立地です。",
    body: [
      { h2: "大和市で子どもにダンスを習わせるなら", p: "3路線が使える大和市は、市内だけでなく相模大野・海老名方面の教室も選択肢に入る通いやすいエリアです。駅から徒歩圏か、3歳から通えるか、週1回から無理なく始められるかを基準に絞り込みましょう。発表会のあるスクールなら目標を持って続けられます。まずは無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "大和市のダンス教室は何歳から通えますか？", a: "大和駅・中央林間駅周辺のスクールには3歳から通えるクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("大和市", "神奈川県") },
  "kanagawa/yokosuka": { name: "横須賀市", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "横須賀市は三浦半島の中心都市で、京急線とJR横須賀線が市内を結びます。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "京急線の横須賀中央駅を中心にスクールが集まり、追浜・久里浜方面など市内各地からも通いやすい立地です。",
    body: [
      { h2: "横須賀市で子どもにダンスを習わせるなら", p: "音楽やストリートカルチャーが根付く横須賀は、子どもがダンスに親しみやすい土壌のある街です。横須賀中央駅周辺は商業施設が集まり、送迎と買い物を兼ねられます。3歳から通えるか、発表会やイベント出演の機会があるか、月謝と諸費用のバランスを比較し、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "横須賀市のダンス教室はどのエリアに多いですか？", a: "横須賀中央駅周辺に教室が集まっているほか、久里浜・追浜方面にも点在しています。京急沿線なら電車での通学もしやすいエリアです。" }],
    schools: areaDanceSchools("横須賀市", "神奈川県") },
  "kanagawa/zushi": { name: "逗子市", prefName: "神奈川県", prefSlug: "kanagawa",
    intro: "逗子市は海と山に囲まれた湘南の住宅都市で、JR横須賀線と京急逗子線で都心方面ともつながります。3歳から通える子ども向けダンス教室を比較しました。",
    access: "JR逗子駅・京急の逗子・葉山駅周辺にスクールが点在し、葉山町・鎌倉市方面からも通いやすい立地です。",
    body: [
      { h2: "逗子市で子どもにダンスを習わせるなら", p: "コンパクトな逗子市は駅周辺に生活機能がまとまり、習い事の送り迎えがしやすい街です。市内の教室に加え、鎌倉・横須賀方面の教室も選択肢に入ります。3歳から通えるか、週1回から無理なく始められるか、発表会で舞台経験を積めるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "逗子市から子どもが通えるダンス教室はありますか？", a: "逗子駅・逗子・葉山駅周辺の教室のほか、横須賀線・京急沿線で鎌倉・横須賀方面の教室にも通いやすい立地です。" }],
    schools: areaDanceSchools("逗子市", "神奈川県") },
  // ── 京都府 ──
  "kyoto/kyoto-city": { name: "京都市", prefName: "京都府", prefSlug: "kyoto",
    intro: "京都市は地下鉄・阪急・京阪・JRが市内を結ぶ、関西第2の都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "地下鉄烏丸線・東西線の沿線や阪急京都線・京阪本線の駅周辺にスクールが点在し、市内11区のどのエリアからも通いやすい環境です。",
    body: [
      { h2: "京都市はキッズダンスの選択肢が豊富", p: "伝統文化の街でありながら学生も多い京都市は、ダンススタジオの層が厚いエリアです。四条烏丸・京都駅周辺など中心部は選択肢が豊富で、住宅エリアの駅近にも教室が点在しています。3歳から通えるか、駅から徒歩圏か、発表会の機会があるかを基準に絞り込み、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "京都市で子どもが通えるダンス教室はどのエリアに多いですか？", a: "四条烏丸・京都駅周辺の中心部に教室が集まっているほか、伏見区・山科区など住宅エリアの駅周辺にも点在しています。地下鉄・私鉄沿線で通いやすい教室を選びましょう。" }],
    schools: areaDanceSchools("京都市", "京都府") },
  // ── 長野県 ──
  "nagano/nagano-city": { name: "長野市", prefName: "長野県", prefSlug: "nagano",
    intro: "長野市は北陸新幹線が停まる長野県の県都で、子ども向け習い事の選択肢が県内で最も豊富なエリアです。3歳から通えるダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "長野駅を中心にしなの鉄道・長野電鉄・バス路線が市内各地へ伸び、車での送迎にも対応しやすいエリアです。",
    body: [
      { h2: "長野市で子どもにダンスを習わせるなら", p: "県都・長野市は常設スタジオを構えるダンススクールもあり、雪の多い冬でも毎週同じ場所で安定して通えます。車での送迎が中心になるご家庭は、駐車のしやすさとレッスン時間帯を確認しましょう。3歳から通えるリトルクラスがあるか、発表会で舞台経験を積めるかも大切な基準です。まずは無料体験でスタジオの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "長野市に常設のダンススタジオはありますか？", a: "長野市内には常設スタジオを構える子ども向けダンススクールがあります。冬場の天候に左右されず通えるのが常設型の利点です。" }],
    schools: areaDanceSchools("長野市", "長野県") },
  // ── 埼玉県 ──
  "saitama/kawaguchi": { name: "川口市", prefName: "埼玉県", prefSlug: "saitama",
    intro: "川口市は荒川を挟んで東京と接する、都内通勤のご家庭が多い埼玉県南部の中核都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR京浜東北線の川口・西川口駅と埼玉高速鉄道沿線にスクールが点在し、蕨市・戸田市方面からも通いやすい立地です。",
    body: [
      { h2: "川口市で子どもにダンスを習わせるなら", p: "共働き世帯の多い川口市では、駅近で送り迎えしやすい教室や、平日夕方・土日にクラスのある教室が人気です。川口駅周辺は商業施設が充実し、買い物と送迎を兼ねられます。3歳から通えるリトルクラスがあるか、振替制度があるかを確認し、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "川口市のダンス教室は何歳から通えますか？", a: "川口駅・西川口駅周辺のスクールには3歳から通えるクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("川口市", "埼玉県") },
  "saitama/koshigaya": { name: "越谷市", prefName: "埼玉県", prefSlug: "saitama",
    intro: "越谷市は越谷レイクタウンの開発で子育て世帯が増え続ける、埼玉県東部の中心都市です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "東武スカイツリーラインの越谷・新越谷駅とJR武蔵野線の南越谷・越谷レイクタウン駅周辺にスクールが点在し、草加市・春日部市方面からも通いやすい立地です。",
    body: [
      { h2: "越谷市で子どもにダンスを習わせるなら", p: "新越谷・南越谷の乗り換えターミナル周辺とレイクタウンエリアに生活機能が集まる越谷市は、習い事の送り迎えがしやすい街です。商業施設内や駅近の教室なら、買い物のついでに通えます。3歳から通えるか、発表会の機会があるか、月謝と諸費用を比較し、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "越谷レイクタウン周辺に子ども向けダンス教室はありますか？", a: "越谷レイクタウン駅・南越谷駅周辺には子ども向けのダンス教室が点在しています。商業施設と合わせて送迎しやすいのがこのエリアの特長です。" }],
    schools: areaDanceSchools("越谷市", "埼玉県") },
  "saitama/minami": { name: "南区", prefName: "埼玉県", prefSlug: "saitama",
    intro: "さいたま市南区は武蔵浦和・南浦和を中心に、都心通勤の子育て世帯が集まる人気エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR埼京線・武蔵野線が交わる武蔵浦和駅と、京浜東北線・武蔵野線の南浦和駅周辺にスクールが集まり、戸田市・蕨市方面からも通いやすい立地です。",
    body: [
      { h2: "南区で子どもにダンスを習わせるなら", p: "武蔵浦和駅周辺は再開発でマンションが増え、子ども向け習い事の需要が高いエリアです。駅近の教室なら、共働きのご家庭でも送り迎えしやすいのが利点です。3歳から通えるリトルクラスがあるか、平日夕方・土日のクラスがあるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "武蔵浦和・南浦和に子ども向けダンス教室はありますか？", a: "武蔵浦和駅・南浦和駅の周辺に子ども向けダンスクラスを設ける教室が点在しています。2路線が使えるため、近隣エリアからも通いやすいです。" }],
    schools: areaDanceSchools("南区", "埼玉県") },
  "saitama/urawa": { name: "浦和区", prefName: "埼玉県", prefSlug: "saitama",
    intro: "さいたま市浦和区は県内屈指の文教エリアとして知られ、教育熱心なご家庭が集まる街です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR浦和駅・北浦和駅の周辺にスクールが集まり、京浜東北線・宇都宮線・高崎線沿線の各エリアからも通いやすい立地です。",
    body: [
      { h2: "文教都市・浦和はダンスと勉強を両立しやすい", p: "学習塾の激戦区として知られる浦和は、習い事と勉強を両立するご家庭が多いエリアです。ダンスはリズム感・体力・表現力を育てながら週1回から始められ、勉強の息抜きにもなります。平日夕方や土曜のクラスがあるか、駅から徒歩圏かを基準に選び、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "浦和区で平日夕方に通えるダンス教室はありますか？", a: "浦和駅・北浦和駅周辺には放課後の時間帯にキッズクラスを設ける教室があります。塾や学校と両立しやすい時間割のスクールを選ぶと続けやすいです。" }],
    schools: areaDanceSchools("浦和区", "埼玉県") },
  // ── 滋賀県 ──
  "shiga/kusatsu": { name: "草津市", prefName: "滋賀県", prefSlug: "shiga",
    intro: "草津市はJR琵琶湖線で京都・大阪方面と直結する、滋賀県内で人口増加が続く子育て人気エリアです。3歳から通える子ども向けダンス教室を比較しました。",
    access: "JR琵琶湖線の草津駅・南草津駅周辺にスクールが集まり、栗東市・大津市方面からも通いやすい立地です。",
    body: [
      { h2: "草津市は子育て世帯が増えるダンス人気エリア", p: "南草津駅周辺を中心にマンションが増え、子どもの数が多い草津市は習い事の環境が整ったエリアです。駅周辺の教室なら電車でも車でも通いやすく、送り迎えの負担を抑えられます。3歳から通えるリトルクラスがあるか、発表会で舞台経験を積めるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "草津市のダンス教室は何歳から通えますか？", a: "草津駅・南草津駅周辺のスクールには3歳から通えるクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("草津市", "滋賀県") },
  "shiga/otsu": { name: "大津市", prefName: "滋賀県", prefSlug: "shiga",
    intro: "大津市は琵琶湖の南西岸に広がる滋賀県の県都で、JR琵琶湖線と京阪電車が市内を結びます。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR大津・膳所・石山駅と京阪石山坂本線の沿線にスクールが点在し、市内各エリアから通いやすい立地です。",
    body: [
      { h2: "大津市で子どもにダンスを習わせるなら", p: "南北に長い大津市では、自宅最寄りの駅周辺から教室を探すのが効率的です。膳所・石山エリアは商業施設も多く、送迎と買い物を兼ねられます。京都方面の教室も電車で通える距離です。3歳から通えるか、週1回から始められるか、発表会の機会があるかを確認し、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "大津市のダンス教室はどのエリアに多いですか？", a: "大津・膳所・石山の各駅周辺に教室が点在しています。京阪石山坂本線沿線は駅間が短く、子どもの通いやすさで選びやすいエリアです。" }],
    schools: areaDanceSchools("大津市", "滋賀県") },
  // ── 東京都 ──
  "tokyo/chofu": { name: "調布市", prefName: "東京都", prefSlug: "tokyo",
    intro: "調布市は京王線で新宿と直結する、緑と利便性のバランスが良い子育てエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "京王線の調布駅を中心に、仙川・つつじヶ丘・国領など各駅の周辺にスクールが点在し、狛江市・三鷹市方面からも通いやすい立地です。",
    body: [
      { h2: "調布市で子どもにダンスを習わせるなら", p: "映画の街として文化的な土壌のある調布市は、子ども向けの習い事も充実したエリアです。調布駅周辺は再開発で商業施設が増え、送迎と買い物を兼ねられます。3歳から通えるリトルクラスがあるか、駅から徒歩圏か、発表会で舞台経験を積めるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "調布市のダンス教室はどの駅周辺に多いですか？", a: "調布駅周辺に教室が集まっているほか、仙川・つつじヶ丘など京王線の各駅周辺にも点在しています。駅徒歩圏の教室なら送り迎えがしやすいです。" }],
    schools: areaDanceSchools("調布市", "東京都") },
  "tokyo/edogawa": { name: "江戸川区", prefName: "東京都", prefSlug: "tokyo",
    intro: "江戸川区は子育て支援の手厚さで知られ、子どもの数が多い東京東部のファミリーエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "東西線の西葛西・葛西駅、都営新宿線の船堀・瑞江駅、JR総武線の小岩駅など、区内各エリアの駅周辺にスクールが点在しています。",
    body: [
      { h2: "江戸川区は子どもの数が多いダンス需要の高いエリア", p: "公園が多く子育て世帯に人気の江戸川区は、キッズダンスの需要が高いエリアです。区内は路線ごとに生活圏が分かれるため、自宅最寄り駅の周辺から教室を探すのが効率的です。3歳から通えるか、平日夕方・土日のクラスがあるか、発表会の機会があるかを基準に選び、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "江戸川区のダンス教室は何歳から通えますか？", a: "西葛西・船堀・小岩など各駅周辺のスクールには3歳から通えるリトルクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("江戸川区", "東京都") },
  "tokyo/kita": { name: "北区", prefName: "東京都", prefSlug: "tokyo",
    intro: "東京都北区は赤羽・王子を中心にJRと地下鉄が走る、都心アクセスの良い住宅エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR京浜東北線・埼京線の赤羽駅、京浜東北線・南北線の王子駅周辺にスクールが集まり、板橋区・荒川区方面からも通いやすい立地です。",
    body: [
      { h2: "北区で子どもにダンスを習わせるなら", p: "赤羽・王子周辺は商業施設と住宅街が近く、習い事の送り迎えがしやすいエリアです。JR・地下鉄の駅から徒歩圏の教室なら、共働きのご家庭でも無理なく通わせられます。3歳から通えるリトルクラスがあるか、振替制度があるか、発表会の機会があるかを確認し、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "北区のダンス教室はどの駅周辺に多いですか？", a: "赤羽駅・王子駅の周辺に子ども向けダンス教室が集まっています。埼京線・京浜東北線・南北線が使え、区内外から通いやすいエリアです。" }],
    schools: areaDanceSchools("北区", "東京都") },
  "tokyo/machida": { name: "町田市", prefName: "東京都", prefSlug: "tokyo",
    intro: "町田市は小田急線とJR横浜線が交わる東京多摩南部の商業都市で、子育て世帯にも人気のエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "小田急線・JR横浜線の町田駅を中心にスクールが集まり、相模原市・多摩市方面からも通いやすい立地です。",
    body: [
      { h2: "町田市はダンス教室の選択肢が豊富", p: "若者文化が根付く町田はダンススタジオの層が厚く、キッズクラスの選択肢も豊富なエリアです。町田駅周辺は商業施設が充実し、送迎と買い物を兼ねられます。選択肢が多いからこそ、3歳から通えるか、発表会があるか、月謝と諸費用のバランスを基準に絞り込み、無料体験を2〜3校受けて比較するのがおすすめです。" },
    ],
    faqs: [{ q: "町田駅周辺に子ども向けダンス教室はありますか？", a: "町田駅周辺には子ども向けダンスクラスを設ける教室が複数あります。小田急・JRの2路線が使え、広いエリアから通いやすいのが特長です。" }],
    schools: areaDanceSchools("町田市", "東京都") },
  "tokyo/meguro": { name: "目黒区", prefName: "東京都", prefSlug: "tokyo",
    intro: "目黒区は中目黒・自由が丘・学芸大学が並ぶ東急東横線沿線の人気住宅エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "東急東横線の中目黒・学芸大学・都立大学・自由が丘の各駅周辺にスクールが点在し、世田谷区・品川区方面からも通いやすい立地です。",
    body: [
      { h2: "目黒区で子どもにダンスを習わせるなら", p: "感度の高いご家庭が多い目黒区は、ダンス・音楽系の習い事が人気のエリアです。東横線沿線は駅徒歩圏の教室が多く、送り迎えしやすいのが特長です。3歳から通えるリトルクラスがあるか、K-POPやヒップホップなどジャンルを選べるか、発表会の機会があるかを基準に選び、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "目黒区のダンス教室はどの駅周辺に多いですか？", a: "中目黒・学芸大学・自由が丘など東横線の各駅周辺に教室が点在しています。駅から徒歩圏の教室なら学校帰りにも通いやすいです。" }],
    schools: areaDanceSchools("目黒区", "東京都") },
  "tokyo/minato": { name: "港区", prefName: "東京都", prefSlug: "tokyo",
    intro: "港区は麻布・白金・青山など都心の住宅地を抱え、教育への関心が高いご家庭が集まるエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "南北線・都営三田線の白金高輪駅や大江戸線の麻布十番駅など、地下鉄各駅の周辺にスクールが点在し、区内外から通いやすい立地です。",
    body: [
      { h2: "港区で子どもにダンスを習わせるなら", p: "インターナショナルな環境の港区は、英語・音楽と並んでダンスを習わせるご家庭が多いエリアです。地下鉄網が発達しているため、駅から徒歩圏かどうかが送り迎えのしやすさを左右します。3歳から通えるリトルクラスがあるか、発表会で舞台経験を積めるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "白金高輪エリアに子ども向けダンス教室はありますか？", a: "白金高輪駅周辺には子ども向けダンスクラスを設ける教室があります。南北線・三田線の2路線が使え、品川・目黒方面からも通いやすい立地です。" }],
    schools: areaDanceSchools("港区", "東京都") },
  "tokyo/nerima": { name: "練馬区", prefName: "東京都", prefSlug: "tokyo",
    intro: "練馬区は西武線と大江戸線が走る、23区内でも子育て世帯の多い住宅エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "西武池袋線の練馬・石神井公園駅、都営大江戸線の光が丘駅周辺にスクールが点在し、区内各地から通いやすい立地です。",
    body: [
      { h2: "練馬区で子どもにダンスを習わせるなら", p: "公園が多く子育てしやすい練馬区は、幼児から小学生まで通えるダンス教室の需要が高いエリアです。光が丘・石神井公園など生活拠点の駅周辺なら、買い物と送迎を兼ねられます。3歳から通えるリトルクラスがあるか、平日夕方・土日のクラスがあるかを基準に選び、無料体験で先生との相性を確かめましょう。" },
    ],
    faqs: [{ q: "練馬区のダンス教室は何歳から通えますか？", a: "練馬・石神井公園・光が丘など各駅周辺のスクールには3歳から通えるクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("練馬区", "東京都") },
  "tokyo/setagaya": { name: "世田谷区", prefName: "東京都", prefSlug: "tokyo",
    intro: "世田谷区は三軒茶屋・二子玉川・成城など多彩な街を抱える、23区最大級の人口を持つ子育てエリアです。3歳から通える子ども向けダンス教室を比較しました。",
    access: "東急田園都市線の三軒茶屋・二子玉川駅、小田急線の下北沢・成城学園前駅など、各沿線の駅周辺にスクールが点在しています。",
    body: [
      { h2: "世田谷区はキッズダンスの激戦区", p: "子どもの数が多い世田谷区は、ダンス教室の選択肢が23区内でも特に豊富なエリアです。沿線ごとに生活圏が分かれるため、自宅最寄り駅の徒歩圏から探すのが効率的です。3歳から通えるか、K-POP・ヒップホップなどジャンルを選べるか、発表会があるかを基準に絞り込み、無料体験を2〜3校受けて比較するのがおすすめです。" },
    ],
    faqs: [{ q: "世田谷区のダンス教室はどのエリアに多いですか？", a: "三軒茶屋・二子玉川・下北沢など主要駅の周辺に教室が集まっています。田園都市線・小田急線・京王線の各沿線で、自宅から通いやすい教室を選びましょう。" }],
    schools: areaDanceSchools("世田谷区", "東京都") },
  "tokyo/shibuya": { name: "渋谷区", prefName: "東京都", prefSlug: "tokyo",
    intro: "渋谷区はダンスカルチャーの中心地として、経験豊富な講師のスタジオが集まるエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "渋谷駅にはJR・東急・京王井の頭線・地下鉄各線が乗り入れ、代々木・恵比寿方面の駅周辺にもスクールが点在しています。",
    body: [
      { h2: "ダンスの聖地・渋谷で子どもが学ぶメリット", p: "ストリートダンス文化の中心地である渋谷は、経験豊富な講師のレッスンを受けやすいエリアです。一方でスタジオの数が多いため、キッズ専門クラスがあるか、3歳から通えるか、保護者の見学・送迎がしやすいかで絞り込むことが大切です。本格志向にも初めての習い事にも対応できる選択肢があります。無料体験で雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "渋谷区のダンス教室は初心者の子どもでも大丈夫ですか？", a: "渋谷区には本格派スタジオだけでなく、3歳からの初心者向けキッズクラスを設ける教室もあります。レベル分けがあるスクールを選べば初めてでも安心です。" }],
    schools: areaDanceSchools("渋谷区", "東京都") },
  "tokyo/shinagawa": { name: "品川区", prefName: "東京都", prefSlug: "tokyo",
    intro: "品川区は大井町・武蔵小山・五反田を中心に、再開発で子育て世帯が増え続ける城南エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR京浜東北線・りんかい線の大井町駅、東急目黒線の武蔵小山駅、JR山手線の五反田駅周辺にスクールが点在し、区内各地から通いやすい立地です。",
    body: [
      { h2: "品川区で子どもにダンスを習わせるなら", p: "マンションの増加で子どもの数が増えている品川区は、キッズダンスの需要が高いエリアです。大井町・武蔵小山周辺は商店街と商業施設が充実し、送迎と買い物を兼ねられます。3歳から通えるリトルクラスがあるか、平日夕方・土日のクラスがあるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "品川区のダンス教室はどの駅周辺に多いですか？", a: "大井町・武蔵小山・五反田の各駅周辺に子ども向けダンス教室が点在しています。駅徒歩圏の教室なら共働きのご家庭でも送り迎えしやすいです。" }],
    schools: areaDanceSchools("品川区", "東京都") },
  "tokyo/shinjuku": { name: "新宿区", prefName: "東京都", prefSlug: "tokyo",
    intro: "新宿区は日本有数のターミナル・新宿駅を擁し、ダンススタジオの選択肢が非常に豊富なエリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "新宿駅にはJR・小田急・京王・地下鉄各線が乗り入れ、高田馬場・四谷方面の駅周辺にもスクールが点在しています。都内全域から通いやすい立地です。",
    body: [
      { h2: "新宿区でダンス教室を選ぶポイント", p: "スタジオ数が多い新宿区では、大人向け中心のスタジオではなく、キッズ専門クラスやレベル分けが整った教室を選ぶことが大切です。ターミナル駅周辺は人通りが多いため、送迎のしやすさや教室までの経路も確認しましょう。3歳から通えるか、発表会があるかを基準に絞り込み、無料体験で先生との相性を確かめるのがおすすめです。" },
    ],
    faqs: [{ q: "新宿区のダンス教室は子ども専門のクラスがありますか？", a: "新宿区には大人向けスタジオが多い一方、3歳からのキッズ専門クラスを設ける教室もあります。年齢・レベル別にクラスが分かれているスクールを選ぶと安心です。" }],
    schools: areaDanceSchools("新宿区", "東京都") },
  "tokyo/suginami": { name: "杉並区", prefName: "東京都", prefSlug: "tokyo",
    intro: "杉並区は荻窪・阿佐ヶ谷・高円寺などJR中央線沿線の街が並ぶ、文化的な土壌のある住宅エリアです。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR中央線の荻窪・阿佐ヶ谷・高円寺駅と、京王井の頭線の永福町・浜田山駅周辺にスクールが点在し、区内各地から通いやすい立地です。",
    body: [
      { h2: "杉並区で子どもにダンスを習わせるなら", p: "音楽・演劇など文化活動が盛んな杉並区は、子どもの表現系習い事への理解が深いエリアです。中央線・井の頭線の駅徒歩圏に教室が点在し、送り迎えしやすいのが特長です。3歳から通えるリトルクラスがあるか、発表会で舞台経験を積めるかを基準に選び、無料体験でクラスの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "杉並区のダンス教室は何歳から通えますか？", a: "荻窪・阿佐ヶ谷・高円寺など各駅周辺のスクールには3歳から通えるクラスを設けているところがあり、未就学のお子さんから始められます。" }],
    schools: areaDanceSchools("杉並区", "東京都") },
  // ── 和歌山県 ──
  "wakayama/wakayama-city": { name: "和歌山市", prefName: "和歌山県", prefSlug: "wakayama",
    intro: "和歌山市はJR和歌山駅と南海和歌山市駅を中心に市街地が広がる和歌山県の県都です。3歳から通える子ども向けダンス教室を月謝・口コミ・無料体験で比較しました。",
    access: "JR和歌山駅・南海和歌山市駅の周辺にスクールが集まり、岩出市・海南市など近隣からも車で通いやすい立地です。",
    body: [
      { h2: "和歌山市で子どもにダンスを習わせるなら", p: "和歌山市は常設スタジオを構えるダンススクールもあり、毎週同じ場所で安定してレッスンを受けられます。車での送迎が中心になるご家庭は、駐車のしやすさとレッスン時間帯を確認しましょう。3歳から通えるリトルクラスがあるか、発表会で舞台に立つ機会があるかも大切な基準です。まずは無料体験でスタジオの雰囲気を確かめましょう。" },
    ],
    faqs: [{ q: "和歌山市に常設のダンススタジオはありますか？", a: "和歌山市内には常設スタジオを構える子ども向けダンススクールがあります。レンタルスタジオ型と違い、毎週同じ場所で安定して通えるのが利点です。" }],
    schools: areaDanceSchools("和歌山市", "和歌山県") },
};

export const ALL_PREFS_LIST = [
  { slug: "osaka", name: "大阪府" }, { slug: "tokyo", name: "東京都" },
  { slug: "kanagawa", name: "神奈川県" }, { slug: "aichi", name: "愛知県" },
  { slug: "gifu", name: "岐阜県" }, { slug: "hyogo", name: "兵庫県" },
  { slug: "ibaraki", name: "茨城県" }, { slug: "ishikawa", name: "石川県" },
  { slug: "kyoto", name: "京都府" }, { slug: "nagano", name: "長野県" },
  { slug: "shiga", name: "滋賀県" }, { slug: "wakayama", name: "和歌山県" },
  { slug: "saitama", name: "埼玉県" }, { slug: "chiba", name: "千葉県" },
  { slug: "fukuoka", name: "福岡県" }, { slug: "hokkaido", name: "北海道" },
  { slug: "miyagi", name: "宮城県" }, { slug: "hiroshima", name: "広島県" },
  { slug: "shizuoka", name: "静岡県" }, { slug: "okayama", name: "岡山県" },
  { slug: "niigata", name: "新潟県" }, { slug: "tochigi", name: "栃木県" },
  { slug: "gunma", name: "群馬県" }, { slug: "mie", name: "三重県" },
  { slug: "nara", name: "奈良県" }, { slug: "fukui", name: "福井県" },
  { slug: "toyama", name: "富山県" }, { slug: "yamanashi", name: "山梨県" },
  { slug: "tottori", name: "鳥取県" }, { slug: "shimane", name: "島根県" },
  { slug: "kochi", name: "高知県" }, { slug: "tokushima", name: "徳島県" },
  { slug: "kagawa", name: "香川県" }, { slug: "saga", name: "佐賀県" },
  { slug: "oita", name: "大分県" }, { slug: "miyazaki", name: "宮崎県" },
  { slug: "okinawa", name: "沖縄県" }, { slug: "kumamoto", name: "熊本県" },
  { slug: "kagoshima", name: "鹿児島県" }, { slug: "nagasaki", name: "長崎県" },
  { slug: "ehime", name: "愛媛県" }, { slug: "yamaguchi", name: "山口県" },
  { slug: "fukushima", name: "福島県" }, { slug: "akita", name: "秋田県" },
  { slug: "yamagata", name: "山形県" }, { slug: "iwate", name: "岩手県" },
  { slug: "aomori", name: "青森県" },
];
